import type { ExplanationSet } from "../explanations";

/** Spanish wording for src/content/explanations.ts, in the same order, set by set. */
export const EXPLANATIONS_ES: Record<ExplanationSet, string[]> = {
  introduction: [
    "La mayordomía parte de que nunca fue todo tuyo. Un auto de la empresa o tu propio sueldo: lo que se pone a tu cuidado merece una administración cuidadosa.",
    "El curso mide por fidelidad, no por cuánto tienes. Puedes ser fiel con poco, así que compararte con alguien que gana más pierde el punto.",
    "La historia de Abraham muestra que la provisión puede llegar en un apuro real, y eso no es motivo para dejar de planear. La confianza y hacer tu parte van juntas.",
    "José guardó grano en los años buenos antes de que llegara el hambre. Un año bueno es la oportunidad de apartar algo para una temporada más escasa.",
    "Las ofrendas del tabernáculo salieron de corazones dispuestos, no de presión, hasta que Moisés tuvo que decir basta. La generosidad verdadera nace de que te importe aquello a lo que das.",
    "El desafío de Josué es decidir, no esperar ni dejar que otro decida por ti. Poner a Dios primero mientras el dinero toma la mayoría de tus decisiones ya es una decisión.",
    "Daniel rechazó la comida del rey cuando nadie miraba. Las convicciones sobre el dinero están hechas para sostenerse aunque nadie se entere.",
    "Un presupuesto es un plan que le dice a tu dinero adónde ir antes de que el mes lo gaste por ti. Por eso funciona más como un mapa que como una jaula.",
    "El crecimiento se apoya en sí mismo con el tiempo, así que empezar temprano le da más tiempo para trabajar. Esperar a tener más renuncia a eso.",
    "El proverbio es claro: el que toma prestado es siervo del que presta. La deuda no es pecado, pero limita tu libertad, y conviene saberlo antes de pedir prestado.",
  ],
  1: [
    "La Escritura dice que Dios es quien da el poder para hacer riqueza. El ingreso es un regalo que se recibe y se administra, no algo que se produce del todo solo.",
    "Con un solo sueldo de un solo empleador, una sola interrupción, como un despido o una enfermedad, puede detener todo el ingreso a la vez. Esa es la fragilidad de la que advierte la lección.",
    "Antes de buscar una nueva fuente, pregunta qué desplazará y cuánto costará en descanso y relaciones. La emoción por sí sola no es motivo para sumarla.",
    "Los límites ubican el problema en el amor al dinero y la prisa por enriquecerse, no en el ingreso mismo. Ninguna cantidad parece suficiente cuando esa es la raíz.",
    "Varias fuentes no impiden las malas noticias, pero cambian cómo cae una pérdida repentina de empleo. Un hogar se queda sin nada; el otro todavía recibe algo.",
    "La prueba de una fuente es si podría seguir produciendo dinero por un tiempo aunque otra se detuviera. No es la paga más alta ni lo bien que se sienta.",
    "Casi ningún ingreso es realmente sin esfuerzo. El ingreso por alquiler se describe mejor como trabajo de otra forma que como ausencia de trabajo.",
    "El trabajo ordinario y digno que sirve a otros es parte del diseño original. Colosenses dice que lo hagas de corazón, como para el Señor, sea cual sea el empleo.",
    "La lección propone avanzar despacio y tratar el descanso como parte de un patrón sostenible, no como premio por terminar. Entregar todas las tardes y fines de semana durante años no es la meta.",
    "Anotar cada fuente, aun las pequeñas u olvidadas, es el primer acto de fidelidad con lo que tienes. No puedes administrar bien lo que no has mirado.",
  ],
  2: [
    "Un depósito solo sirve si se llena en la temporada buena. Apartar parte del bono ahora es lo que hizo José antes de los años escasos.",
    "La hormiga no tiene jefe ni gran ingreso, y aun así se prepara. La lección es el hábito de prepararse, no la gran fuerza.",
    "El almacén del rico insensato era solo para sí mismo, sin lugar para Dios ni para otros, y solo daba una falsa seguridad. Ahorrar es sabio; acumular para uno mismo no.",
    "Una meta se vuelve concreta con cuatro cosas: un propósito, una cantidad, una fecha y un ritmo. Un deseo vago de ahorrar más no te dice qué hacer el viernes.",
    "Una cantidad pequeña y regular forma el hábito, mantiene la meta a la vista y sobrevive a los cambios de ánimo, algo que un depósito único no logra. Cinco dólares a la semana cuentan.",
    "Pagarte primero es mover una cantidad fija al ahorro apenas llega el ingreso, antes de gastar nada. Ahorrar lo que sobra casi nunca deja nada.",
    "El interés de una deuda costosa suele superar lo que el ahorro podría ganar, y eso anula el beneficio de ahorrar. Por eso la deuda costosa necesita atención urgente.",
    "Un periodo de espera de unos días deja que se apague el impulso de comparar y comprar. Forma contentamiento sin prohibirte comprar para siempre.",
    "El orden de la lección es un pequeño colchón inicial, luego la deuda costosa, luego un colchón más completo y después las metas de largo plazo. El prudente ve venir el problema y se prepara en una secuencia sensata.",
    "Presentarte con honestidad con una cifra pequeña es el hábito que forma la práctica. Apartar algo, como Pablo dijo a los corintios, empieza con una primera cantidad, no con una perfecta.",
  ],
  3: [
    "En la parábola, enterrar el dinero no fue seguro ni neutral; fue un fracaso. Dejar quieto un dinero inesperado mientras pierde terreno es otra forma de fracasar.",
    "La riqueza que se busca con prisa es una advertencia, y los rendimientos altos casi sin riesgo, con presión por decidir rápido, son justo las señales para frenar. La presión por decidir ya es parte del patrón.",
    "Tus capacidades son recursos que pueden desarrollarse o dejarse sin usar, como cualquier otro. Por eso invertir en ti va primero y rinde por más tiempo.",
    "El agricultor siembra y luego espera la hierba, la espiga y el grano lleno, en un proceso que nadie controla del todo. El crecimiento real suele ser gradual y no se puede apresurar.",
    "El inversionista prudente primero hace preguntas sencillas: qué es, cómo gana y cuánto cuesta. Entregar dinero porque un amigo lo recomendó es esperanza, no comprensión.",
    "Con todo en un solo lugar, una sola decepción puede ser devastadora porque no hay nada más que la amortigüe. Repartir el riesgo es lo que aconseja Eclesiastés.",
    "Un curso o un mentor afina la capacidad que produce otros ingresos, y por eso es una de las primeras inversiones y de las que rinden más tiempo. No es solo para los ricos.",
    "La balanza falsa es abominación, así que el origen de una ganancia importa. La ganancia honesta es esencialmente distinta de la deshonesta, aunque sea la misma cantidad.",
    "Proverbios une una y otra vez la seguridad y los buenos planes con buscar consejo. Una decisión grande tomada totalmente a solas se salta una de las protecciones que más repite la Escritura.",
    "No estar invirtiendo todavía puede ser el momento de preguntarte con honestidad por qué y qué tendría que cambiar para empezar. La práctica busca iniciar esa conversación, no calificarte.",
  ],
  4: [
    "Todo ya pertenece a Dios: la plata y el oro son suyos. Dar es devolver una parte de lo que nunca fue del todo nuestro.",
    "Las primicias significan dar primero, antes de gastar el resto. Dar lo que sobra suele quedar en nada, porque los gastos que crecen lo consumen.",
    "Dios ama al dador alegre. El corazón y el motivo detrás de una ofrenda importan más que su tamaño o un cumplimiento a regañadientes.",
    "La lección empieza por los más cercanos: familia, vecinos, compañeros de trabajo y hermanos de la iglesia. Las necesidades cercanas son reales, y Santiago muestra que las palabras solas no las cubren.",
    "Sembrar y cosechar describe un principio de generosidad, no una fórmula que obligue a Dios a pagar con dinero. Tratarlo como una transacción presiona a la gente a dar lo que no puede.",
    "Un registro privado es para la mayordomía: ver si tu dar coincide con tus intenciones. No es para ganar crédito público, así que encaja con la enseñanza de Jesús sobre dar en secreto.",
    "La instrucción de Pablo sostiene ambas cosas: no pongas tu esperanza en las riquezas y está dispuesto a compartir. La riqueza se vuelve un recurso en lugar de un amo.",
    "Ganar, ahorrar e invertir sin dar puede convertir poco a poco a alguien en quien cuida un montón en lugar de ser un canal. Dar mantiene el agua en movimiento.",
    "Un plan sencillo decide de antemano la porción, los destinatarios y el momento. Eso cambia el impulso por la intención.",
    "Dar va en cuarto lugar porque completa el cuadro: el agua que se juntó y se puso a trabajar también tiene que volver a fluir hacia afuera. Se conecta con los otros tres, no está aparte.",
  ],
  exam: [
    "La advertencia a un Israel próspero fue recordar al SEÑOR, quien da el poder para hacer riqueza. El orgullo en la propia astucia olvida de dónde vino la capacidad.",
    "Un administrador sostiene lo que se le confió, y eso tiende a producir gratitud junto con un sentido de responsabilidad. El derecho y la ansiedad crecen desde la idea de que \"todo es mío\".",
    "Pablo dice que trabajes de corazón, como para el Señor y no para los hombres. Así que el esfuerzo completo y honesto corresponde a todo empleo, por pequeño que parezca.",
    "Pablo les dijo a los tesalonicenses que si alguien no quiere trabajar, tampoco coma. La provisión no es motivo para dejar de trabajar.",
    "Eclesiastés dice que repartas una porción entre siete, y aun ocho, porque no sabes qué desastre pueda venir. Apunta a repartir lo que tienes en lugar de depender de una sola fuente.",
    "Además del ingreso del trabajo y del negocio, el curso nombra el ingreso de activos y el ingreso creativo o intelectual. Un sueldo es solo un tipo de fuente.",
    "El dinero de alquilar una unidad extra viene de algo que posees, así que es ingreso de activos. Es distinto de ganar un salario o dirigir un negocio.",
    "Casi ningún ingreso es realmente sin esfuerzo. El ingreso por alquiler es trabajo de otra forma, no ausencia de trabajo, así que las solicitudes de mantenimiento siguen importando.",
    "Pablo trabajó como fabricante de tiendas junto a Priscila y Aquila mientras ministraba. El oficio y el ministerio no eran enemigos.",
    "La Escritura señala a Lidia, vendedora de púrpura, como una empresaria fiel y generosa. El negocio y la fe van juntos.",
    "La lección de los límites llama gotera a una fuente de ingreso que te cuesta la honestidad. Drena algo que vale más que el dinero que trae.",
    "El tamaño de una meta de ingresos debe venir del propósito que tienes para él, no de lo que gana un vecino ni del número más alto que puedas imaginar.",
    "Más de una fuente no evita que lleguen malas noticias. Cambia cómo cae sobre el hogar la pérdida repentina de una de ellas.",
    "La hormiga no tiene jefe ni gran ingreso, y aun así se prepara. Prepararse requiere el hábito de hacerlo con constancia, no gran fuerza.",
    "Los hogares con poco margen tienen más que perder ante una sorpresa, así que tienen la razón más fuerte para empezar, aun con cantidades pequeñas.",
    "Jesús respondió a la petición del hombre con la parábola del rico insensato porque su enfoque en recibir su parte revelaba un problema del corazón mayor que la cuestión legal.",
    "El proverbio dice que prepares tu labor afuera antes de edificar tu casa. La preparación de fondo debe ir antes de los detalles finales.",
    "Una meta de ahorro se vuelve concreta con un propósito, una cantidad, una fecha y un ritmo. \"Ahorrar más este año\" no tiene ninguno.",
    "El orden de la lección es un pequeño colchón inicial, luego la deuda costosa, luego un colchón más completo y después las metas de largo plazo. Es una secuencia, no todo a la vez.",
    "Zacarías preguntó quién ha menospreciado el día de las pequeñas cosas. Una cantidad pequeña ahorrada no es motivo de vergüenza.",
    "Un depósito pequeño y regular forma el hábito, mantiene la meta a la vista y sobrevive a los cambios de ánimo. Uno grande y ocasional a menudo no puede.",
    "El Salmo 37 dice que los íntegros tendrán abundancia en tiempos de hambre. La integridad es parte de cómo se promete que la provisión se sostiene.",
    "Pablo dice que quien no provee para sus parientes ha negado la fe. Dar en la iglesia no reemplaza la responsabilidad con la familia.",
    "Con un colchón pequeño ya hecho, el orden dice que te enfoques en la deuda costosa sin dejar de ahorrar algo. Dejar de ahorrar por completo te deja expuesto.",
    "Un periodo de espera de unos días deja que se apague el impulso de copiar la compra de un amigo. Forma contentamiento sin prohibirte comprar.",
    "En la parábola de los talentos, cada siervo recibió según su propia capacidad. No fue igual para todos, ni una lotería, ni por antigüedad.",
    "El amo dijo que el tercer siervo debió al menos poner el dinero con los banqueros para que ganara interés. Enterrarlo fue lo único que no ganó nada.",
    "Proverbios dice que el que se apresura a enriquecerse no quedará sin castigo, y que la riqueza que se consigue de prisa no será bendecida al final. La prisa es la advertencia.",
    "Los rendimientos altos con poco o ningún riesgo son una señal de alerta. Un horizonte largo no lo es; es simplemente la forma en que muchas cosas buenas rinden.",
    "Dios llenó a Bezaleel de habilidad para el trabajo artesanal fino. El trabajo manual y el diseño pueden ser un don espiritual.",
    "Pablo le dijo a Timoteo que avivara el fuego del don de Dios. Las capacidades sin usar se apagan, así que vale la pena cuidarlas y desarrollarlas.",
    "El hierro con hierro se afila apunta al valor de la mentoría y el consejo de otros. Aprender todo a solas renuncia a eso.",
    "La semilla de Jesús crece primero la hierba, luego la espiga y después el grano lleno. El crecimiento es gradual, en un proceso que nadie controla del todo, así que revisar cada día no lo acelera.",
    "Santiago compara la paciencia con el agricultor que espera las lluvias tempranas y tardías. La cosecha llega a su tiempo, no a pedido.",
    "El interés compuesto es el crecimiento que a su vez crece con el tiempo. Por eso empezar temprano, aunque sea poco, vale tanto.",
    "El prudente medita sus pasos, y el simple todo lo cree. La molestia de un vendedor ante preguntas razonables es información, igual que una respuesta vaga o evasiva.",
    "Repartir una porción entre siete, y aun ocho, respalda diversificar las inversiones en lugar de concentrarlo todo en un solo lugar. No sabes qué desastre pueda venir.",
    "La balanza falsa es abominación al SEÑOR. Una ganancia que depende de engañar a la otra parte es ganancia deshonesta, aunque sea técnicamente legal.",
    "El SEÑOR dice que la plata y el oro son suyos. La riqueza pertenece en última instancia a Dios; la tenemos y la administramos, no somos dueños absolutos.",
    "La oración de David muestra humildad: aun la capacidad de dar con generosidad es un regalo. Coincide con la pregunta de Pablo: \"¿Qué tienes que no hayas recibido?\"",
    "Pablo preguntó a los corintios: \"¿Qué tienes que no hayas recibido?\" Eso desmonta la idea de que todo vino de tu propio esfuerzo.",
    "Después de su victoria, Abraham dio el diezmo de todo a Melquisedec, mucho antes de la ley de Moisés. Devolver una parte del aumento vino antes de ser un mandato formal.",
    "Bajo la ley de Moisés el diezmo era la décima parte del producto de la tierra, y pertenecía al Señor.",
    "Jesús dirigió su reprensión por diezmar la menta, el eneldo y el comino mientras se descuidaban la justicia y la misericordia a los fariseos y escribas. Acertar el porcentaje exacto no es toda la obediencia.",
    "Que tu izquierda no sepa lo que hace tu derecha: dar debe hacerse sin buscar atención ni espectáculo.",
    "El curso señala dejar sin cosechar las orillas de los campos y liberar deudas periódicamente, formas continuas y prácticas de proveer a los pobres más allá de regalos ocasionales.",
    "Como siempre habrá pobres entre nosotros, Deuteronomio dice que abras tu mano a tu hermano, al necesitado y al pobre. La necesidad constante es la razón para dar, no una excusa.",
    "Santiago pregunta de qué sirve decir \"id en paz, calentaos y saciaos\" sin dar lo necesario. La compasión sin acción no ayuda realmente.",
    "Fue Pablo quien le dijo a Timoteo que mandara a los ricos no poner su esperanza en las riquezas inciertas sino en Dios, y estar listos para compartir. Disfrutar lo que tienes sin anclar tu esperanza en ello es ese equilibrio.",
    "Hábitos firmes de ganar, ahorrar e invertir sin dar pueden convertir poco a poco a alguien en quien guarda un montón en lugar de dirigir un canal. Dar mantiene el agua en movimiento.",
  ],
};
