import type { IntroductionText } from "./types";

/** Spanish text of the introduction. The verses stay in content/lessons/introduction.ts. */
export const INTRODUCTION_TEXT: IntroductionText = {
  title: "Introducción: Mayordomía",
  intro:
    "Antes de adentrarnos en los ingresos, el ahorro, la inversión y la generosidad, vale la pena dedicar un poco de tiempo a la idea que está debajo de los cuatro: la mayordomía. Esta introducción mira a un puñado de personas de las Escrituras que modelaron distintas partes de ella mucho antes de que alguien lo llamara finanzas personales, además de algunas herramientas prácticas y cotidianas que conviene entender temprano: el presupuesto, cómo crece el dinero con el tiempo y cómo funcionan realmente la deuda y el crédito. Nada de esto es complicado, y nada necesita un registro. Es simplemente el fundamento sobre el que se construyen los cuatro ríos.",
  lessons: [
    {
      title: "¿Qué es la mayordomía?",
      body: [
        "Las Escrituras abren con una afirmación que cambia la manera de leer todo lo que sigue. La tierra y todo lo que hay en ella le pertenece a Dios, no a las personas que la ocupan, la cultivan o terminan poniéndole precio. Cuando Dios coloca a los primeros seres humanos en ese mundo, no les entrega una escritura de propiedad. Les da un trabajo: fructificar, llenar la tierra y ejercer dominio sobre ella. Dominio aquí no significa propiedad. Significa responsabilidad. La primera tarea que se le dio a una persona fue administrar algo que pertenecía a otro.",
        "Esa diferencia entre administrador y dueño es toda la idea de la mayordomía en una sola frase. Un dueño no le responde a nadie y puede hacer lo que quiera con lo suyo. Un mayordomo administra la propiedad de otro y se le juzga por una sola cosa: la fidelidad. No por cuánto tenía al empezar, ni por lo impresionantes que se vieran los resultados desde afuera, sino por si se podía confiar en él con lo que se puso en sus manos. Pablo lo dice con claridad: lo que se requiere de los administradores es que cada uno sea hallado fiel. Esa palabra, fiel, es la vara de medir a la que este curso vuelve una y otra vez.",
        "Este curso está organizado alrededor de una imagen del Génesis: un río que sale de un huerto y se divide en cuatro. En los módulos que siguen, esa fuente se divide en ingresos, ahorro, inversión y generosidad, cuatro partes distintas del mismo trabajo de administrar con fidelidad. Antes de llegar a ellas, esta introducción mira brevemente a personas de las Escrituras que modelaron partes de ese trabajo mucho antes de que existiera una cuenta corriente, además de algunas herramientas prácticas y poco vistosas que conviene entender desde el principio. Nada de esto es complicado. Todo vale la pena hacerlo bien desde el comienzo.",
      ],
    },
    {
      title: "Abraham y José: confianza y previsión",
      body: [
        "Abraham dejó todo lo que le era familiar (su país, su familia extendida, su propia historia) porque Dios se lo dijo, confiando en una promesa que no viviría para ver cumplida del todo. Años después esa misma confianza apareció en un momento más duro, en una montaña, con su hijo a su lado y sin ninguna salida visible a una situación imposible. Abraham dijo que Dios mismo proveería. Y Dios proveyó, y Abraham le puso nombre al lugar en recuerdo de eso: el Señor proveerá. La mayordomía comienza aquí, antes de cualquier conversación sobre presupuestos o porcentajes. Es una confianza tranquila en que la provisión pertenece en última instancia a Dios, y no a nuestra previsión ni a nuestra habilidad para planear, aun cuando el camino no esté claro.",
        "Esa confianza también se vio en la mano abierta de Abraham. Al volver de rescatar a su sobrino Lot en la batalla, le dio la décima parte de todo lo que había recuperado a Melquisedec, sacerdote del Dios Altísimo, mucho antes de que existiera mandamiento alguno de diezmar. En Abraham, la confianza y la generosidad eran la misma actitud, dirigida en dos direcciones.",
        "José, generaciones después, modeló otra virtud: la previsión. Dotado con la capacidad poco común de interpretar los sueños de Faraón, siete años de abundancia seguidos de siete años de hambre, no se detuvo en la predicción. Armó un plan. Guardar una parte de la cosecha de cada año bueno para que los años malos no fueran una catástrofe. Funcionó. Egipto sobrevivió al hambre, y con el tiempo también sobrevivió la propia familia hambrienta de José. Nada de ese plan era ingenioso. Era paciente y poco vistoso, y exigía hacer hoy algo que solo una temporada futura necesitaría.",
        "Dos escenas distintas, una misma forma por debajo. Confiar en Dios lo suficiente como para sostener lo que tienes con la mano abierta, y dar hoy los pasos pacientes y ordinarios que una temporada futura va a exigir. La confianza de manos abiertas y la previsión práctica, juntas, son casi todo este curso en miniatura.",
      ],
    },
    {
      title: "Moisés y Josué: valentía con lo que se te confía",
      body: [
        "Moisés creció con acceso a la riqueza y la posición de la casa misma de Faraón, casi toda la seguridad financiera que el mundo antiguo podía ofrecer a alguien. Hebreos lo elogia después por algo que casi nadie en su posición escogería. Se alejó de todo eso: rehusó el título, prefirió ser maltratado junto con un pueblo esclavizado antes que gozar de los placeres pasajeros de Egipto, y consideró que el oprobio que venía con esa decisión valía más que todos los tesoros de Egipto. Sean cuales sean los recursos que lleguen a tus manos, el ejemplo de Moisés pregunta algo más difícil que cuánto. Pregunta para qué, y para quién.",
        "Décadas después, liderando al pueblo mismo con el que había decidido sufrir, Moisés se topó con un problema que a la mayoría de los líderes les encantaría tener: demasiada generosidad. Cuando se le pidió a Israel que trajera materiales para construir el tabernáculo, trajeron tanto que los artesanos volvieron a decirle que los detuviera. Tuvo que dar una orden para frenar las ofrendas. Es un problema extraño y feliz, y dice algo que vale la pena recordar. Una comunidad que realmente ha captado la visión de lo que está construyendo rara vez necesita que la convenzan de ser generosa. El trabajo más difícil, a veces, es saber cuándo ya se ha dado suficiente.",
        "Josué heredó el liderazgo después de Moisés y, cerca del final de su propia vida, reunió al pueblo para uno de los desafíos más citados de las Escrituras. Escojan hoy a quién servirán. Yo y mi casa, dijo, serviremos al Señor. La mayordomía no consiste solo en entender los principios correctos. Consiste en decidir de verdad, en voz alta, y luego vivir dentro de esa decisión cada día ordinario que sigue: la misma disciplina que se necesita para empezar de verdad a ahorrar, abrir el registro o pagarte a ti primero en lugar de pensar hacerlo algún día, cuando las cosas se calmen.",
      ],
    },
    {
      title: "Daniel: integridad cuando nadie está mirando",
      body: [
        "Daniel era un adolescente llevado cautivo a Babilonia, a quien le ofrecieron un lugar en la mesa misma del rey, con la comida y el vino más ricos que el imperio podía dar, y los rechazó sin hacer ruido. Pidió permiso para comer algo más sencillo, porque aceptar aquello habría comprometido una convicción que casi nadie más en ese palacio compartía ni habría notado que él guardaba. Nadie lo estaba vigilando. La concesión habría sido pequeña, privada y fácil de justificar. Dijo que no de todos modos.",
        "Décadas más tarde, ya mayor y más poderoso que casi cualquiera en el reino, funcionarios envidiosos revisaron todo su historial, administrativo, financiero, personal, buscando algo que usar en su contra, y no encontraron nada. El veredicto de las Escrituras es directo: no pudieron hallar corrupción en él, porque era digno de confianza. Esa clase de reputación no se construye en una sola crisis. Es el rendimiento lento de años de integridad pequeña y poco vistosa. El mismo joven que rechazó la comida del rey es el funcionario que, décadas después, no pudo ser atrapado en nada.",
        "La mayor parte de la integridad financiera es justamente así de invisible. Nadie está auditando si dijiste la verdad completa sobre un gasto, si resististe un atajo que nadie habría descubierto o si cumpliste una promesa pequeña cuando habría sido fácil dejarla pasar. El ejemplo de Daniel dice que esos momentos sin testigos son justo donde se construye una vida digna de confianza, una decisión ordinaria a la vez, mucho antes de que alguien esté revisando.",
      ],
    },
    {
      title: "Presupuesto: decirle a tu dinero a dónde ir",
      body: [
        "A mucha gente un presupuesto le suena restrictivo, como una jaula hecha para impedirte gastar dinero que ya tienes. En realidad es lo contrario: un plan que le dice a tu dinero a dónde ir antes de que el mes lo gaste por ti sin preguntarte. Jesús hizo una versión de este argumento ante una multitud que lo seguía, usando una imagen de la construcción. Supongamos que quieres construir una torre. ¿No te sentarías primero a calcular si realmente puedes terminarla? Sáltate ese paso y terminas con una torre a medio construir y una multitud riéndose de ti. Un presupuesto es ese momento de sentarse a calcular, repetido cada mes en lugar de una sola vez.",
        "Proverbios ofrece una imagen relacionada de la vida del campo: conoce bien el estado de tus ovejas y pon tu corazón en tus rebaños, porque las riquezas no duran para siempre. Quien realmente sabe lo que tiene, hasta el detalle, lo administra distinto que quien solo adivina. Un presupuesto no es más que conocer el estado de tu rebaño en dólares: lo que entra, lo que ya está comprometido y lo que queda por decidir a propósito.",
        "Los planes del diligente tienden a la abundancia, dice Proverbios en otro lugar, mientras que los atajos apresurados no llevan a nada bueno. Un presupuesto no tiene que ser complicado para funcionar. Anota lo que entra. Anota lo que tiene que salir. Decide a propósito a dónde va el resto, en lugar de enterarte por accidente cerca del final del mes. Haz eso con constancia y casi todo lo que sigue en este curso, el ahorro, la inversión, la generosidad, se vuelve más fácil, porque ya sabrás con qué cuentas realmente. La calculadora de abajo es un lugar para probarlo: anota lo que entra, dale a cada dólar un lugar a dónde ir y descarga tu plan cuando cada casilla esté llena.",
      ],
    },
    {
      title: "El valor del dinero en el tiempo",
      body: [
        "Una de las ideas más útiles y menos glamorosas de las finanzas personales es esta: el dinero disponible ahora vale más que la misma cantidad después, porque el dinero puesto a trabajar tiene tiempo para crecer. Eclesiastés lo expresa en una sola imagen memorable. Echa tu pan sobre las aguas, y lo hallarás después de muchos días. Describe una acción que no da fruto de inmediato y que hay que sostener con confianza a través de una demora, que es justamente la forma de dejar que el dinero crezca en lugar de gastarlo en el momento en que llega.",
        "El mecanismo detrás de esto es el interés compuesto, el crecimiento que a su vez crece. Proverbios describe la versión paciente con sencillez: el dinero que se junta poco a poco crece. La matemática más profunda es que las cantidades pequeñas, tempranas y constantes a menudo superan a las cantidades mayores y tardías, simplemente porque el dinero temprano tuvo más tiempo para componerse. La calculadora de aquí abajo te permite ver esto con tus propios números, y el río de la inversión vuelve a ello con una mirada más larga, pero el principio vale la pena sembrarlo ahora. Empezar hoy, aun con muy poco, suele ser mejor que esperar un momento mejor, porque un momento mejor con menos tiempo restante muchas veces no puede compensar la diferencia, por más dinero que llegue después.",
        "El lugar donde está el dinero también importa. El dinero guardado en ahorro está hecho para la seguridad y el acceso rápido, así que suele crecer despacio, mientras que el dinero invertido en un vehículo asume riesgo pero tiene espacio para componerse mucho más rápido en los mismos años. La parábola de los talentos de Jesús trata justamente de esto. Al siervo que enterró su talento lo reprendieron por dejarlo ocioso por miedo, aunque no había perdido nada de él, mientras que a los siervos que pusieron el suyo a trabajar los elogiaron. El ahorro tiene su lugar, y el Río 2 defiende ese caso, pero un mayordomo se pregunta para qué es cada dólar y si está cumpliendo ese trabajo. El Río 3 vuelve a la parábola completa.",
        "Nada de esto es una fórmula para riquezas garantizadas, y nada aquí promete un rendimiento. Los mercados y las inversiones concretas pueden perder valor, y de hecho lo pierden. Es simplemente matemática que juega a tu favor cuando cooperas con el tiempo en lugar de ignorarlo o de correr contra él.",
      ],
    },
    {
      title: "Crédito y deuda en las Escrituras",
      body: [
        "La palabra crédito viene del latín que significa creer o confiar. Cuando un prestamista extiende crédito, confía en que el dinero será devuelto, y un puntaje de crédito es un número que resume qué tan confiablemente alguien ha devuelto lo que pidió prestado en el pasado. Es solo un registro del historial de pagos, no un juicio sobre el carácter, pero acompaña a las personas en algunos de los momentos financieros más grandes de la vida adulta: alquilar un apartamento, financiar un auto, calificar para una hipoteca y, a veces, hasta una solicitud de empleo.",
        "Los puntajes suelen construirse con un puñado de factores ordinarios: si los pagos se han hecho a tiempo, cuánto del crédito disponible se está usando, cuánto tiempo llevan abiertas las cuentas y con qué frecuencia se ha buscado crédito nuevo. Pedir prestado tampoco es gratis. El interés es el precio de usar el dinero de otra persona, por eso el mismo préstamo puede costar cantidades muy distintas según su tasa y su duración. Saber eso hace que un estado de cuenta de un préstamo sea mucho más fácil de leer.",
        "Las Escrituras sí hablan directamente de esto. Proverbios observa que el que toma prestado es siervo del que presta. El salmista contrasta al impío, que toma prestado y no paga, con el justo, que tiene misericordia y da. Pablo escribe: no deban a nadie nada, sino el amarse unos a otros. El hilo común es que la deuda es una obligación real, un derecho que otra persona tiene sobre tus ingresos futuros, y que pagar lo que se debe se trata como cuestión de carácter y no solo de conveniencia.",
        "Cómo aplicar estos versículos es algo que cristianos reflexivos sopesan de manera distinta. Algunos los leen como una advertencia amplia sobre pedir prestado, otros como un llamado a cumplir fielmente cada obligación sin importar lo que se haya pedido, y otros señalan que las Escrituras también describen el prestar como un acto de generosidad. Este curso no te dice qué hacer con los préstamos o el crédito. Esas son decisiones tuyas, de tu familia y de las personas en quienes confías. El propósito aquí es solo ayudarte a entender cómo funcionan el crédito y la deuda, y qué dicen las Escrituras sobre ellos, para que esas decisiones sean más fáciles de pensar.",
      ],
    },
    {
      title: "Antes de comenzar",
      body: [
        "Un puñado de personas, un puñado de ángulos distintos sobre el mismo trabajo de fondo. Abraham confió en la provisión de Dios y dio con libertad antes de que alguien se lo exigiera. José planeó con paciencia para un hambre años antes de que llegara. Moisés rechazó una riqueza que no era suya para quedarse, y más tarde tuvo que frenar una generosidad que se había vuelto demasiada. Josué hizo su compromiso en voz alta y vivió dentro de él. Daniel se mantuvo limpio en los momentos pequeños y sin testigos, año tras año, mucho antes de que alguien estuviera revisando. Ninguno tenía una cuenta corriente, un puntaje de crédito ni una hoja de cálculo de presupuesto. Cada uno de ellos todavía tiene algo que enseñarle a cualquiera que sí los tenga.",
        "A partir de aquí, el curso sigue la imagen hacia la que ha venido avanzando esta introducción: un río que se divide en cuatro. El Río 1 mira los ingresos, de dónde viene realmente la provisión y por qué depender de una sola fuente es frágil. El Río 2 mira el ahorro, guardar una parte a propósito para la temporada que todavía no ha llegado. El Río 3 mira la inversión, el trabajo paciente y honesto con lo que se te ha dado. El Río 4 mira la generosidad, dejar que lo que entra también fluya de regreso hacia afuera. Cada uno termina con un paso pequeño y real anotado en un registro, sencillo a propósito, real y no hipotético.",
        "Nada de esto es una meta que se cruza una sola vez. Es una práctica, igual que la integridad de Daniel y la paciencia de José fueron prácticas, construidas en días ordinarios y no demostradas en un solo día dramático. No nos cansemos de hacer el bien, escribe Pablo, porque a su tiempo cosecharemos, si no desmayamos. Esa es toda la actitud que este curso te pide. Sigue adelante. El río sigue corriendo, directo hacia el Río 1.",
      ],
    },
  ],
};
