import type { RiverText } from "./types";

/** Spanish text of River 3. The verses stay in content/lessons/river3.ts. */
export const RIVER3_TEXT: RiverText = {
  title: "Inversión",
  intro:
    "El primer río amplió de dónde viene tu provisión. El segundo retuvo una parte. El tercero la envía a trabajar. Invertir es la práctica de poner recursos en algo que puede crecer con el tiempo, en lugar de dejarlos ociosos, y Jesús lo trató como un asunto de fidelidad y no de simple astucia. Esta lección es educativa. Te enseñará principios que respaldan tanto las Escrituras como la experiencia ordinaria, como la paciencia, entender lo que posees, repartir el riesgo, la ganancia honesta y la humildad ante el futuro. No te dirá qué comprar, no predecirá ningún mercado ni ofrecerá consejo personal, y nada en ella es una promesa de rendimientos. Las inversiones pueden perder valor, y las decisiones sobre inversiones concretas le corresponden a un profesional con licencia que conozca tu situación completa. El registro del final es un simple diario de tus aportaciones, no un analizador de carteras.",
  practicePrompt: "Anota una aportación de inversión que hayas hecho o que planees hacer este mes.",
  lessons: [
    {
      title: "El dinero del señor",
      body: [
        "Jesús contó una historia que ha moldeado la visión cristiana del dinero durante dos mil años. Un hombre que se prepara para viajar confía su propiedad a tres siervos. A uno le da cinco talentos, a otro dos y a otro uno, a cada uno según su capacidad. Un talento era una suma grande, más o menos el salario de muchos años. Los dos primeros siervos ponen el dinero a trabajar de inmediato y lo duplican. El tercero cava un hoyo y entierra el dinero de su señor en la tierra.",
        "Cuando el señor regresa, arregla cuentas. A los dos primeros les dice las mismas cálidas palabras: bien, buen siervo y fiel. Sobre poco has sido fiel, sobre mucho te pondré. Entra en el gozo de tu señor. El tercer siervo ofrece una explicación. Dice que sabía que su señor era un hombre duro, que tuvo miedo y que escondió el talento en la tierra, y aquí tiene lo que le pertenece. La respuesta del señor es severa. Llama al siervo malo y negligente, y señala que, por lo menos, el dinero pudo haberse puesto con los banqueros, para que al volver hubiera ganado intereses.",
        "Hay varias cosas que vale la pena notar. Primero, el dinero nunca fue de los siervos. Pertenecía al señor, y ellos eran sus administradores. Esto es coherente con todo lo que vimos en el primer río. Segundo, lo que el señor elogió fue la fidelidad, no el tamaño del rendimiento. El siervo de los dos talentos y el de los cinco recibieron exactamente las mismas palabras. Tercero, el fracaso no fue un mal resultado. Fue la inacción provocada por el miedo. Incluso el paso cauteloso de depositar el dinero con los banqueros habría satisfecho al señor.",
        "Esta historia suele citarse para justificar asumir riesgos agresivos, y esa es una mala lectura. No te dice que asumas ningún riesgo en particular. Te dice que enterrar no es neutral. El dinero que se queda ocioso por décadas, perdiendo terreno en silencio frente al alza de los precios, no se ha mantenido seguro. Se ha mantenido pequeño. La alternativa a enterrar no es apostar. Es una mayordomía reflexiva, paciente y preparada.",
      ],
    },
    {
      title: "Entre enterrar y apostar",
      body: [
        "Si la parábola advierte contra la zanja de enterrar, las Escrituras son igual de claras sobre la zanja opuesta. Proverbios dice que el hombre avaro corre tras la riqueza y no sabe que la miseria vendrá sobre él. Otro proverbio advierte que los bienes que se adquieren de prisa al principio no serán al final bendecidos. El tema es la velocidad. La mayordomía sabia rara vez es rápida. El impulso de hacerse rico pronto es una de las trampas más viejas del mundo, y se ha repetido en cada generación con un nombre nuevo.",
        "Un segundo proverbio hace el contraste en términos positivos: la riqueza lograda de la noche a la mañana pronto desaparece, pero la que es fruto del arduo trabajo aumenta con el tiempo. La frase aumenta con el tiempo merece subrayarse. Describe un enfoque basado en la participación constante y no en apuestas dramáticas. La mayoría de las historias de personas que perdieron fortunas en una temporada involucran a alguien a quien se le prometió un rendimiento demasiado bueno para ser verdad, o que pidió prestado para invertir, o que puso todo en una sola idea porque se sentía segura.",
        "Una manera útil de ver las dos zanjas es como dos clases de miedo y orgullo. Enterrar es miedo: el miedo a perder, tan fuerte que ningún riesgo es tolerable. Apostar es orgullo: la convicción de que puedo ser más listo que las probabilidades, o de que esta vez es distinto. El camino entre ambos es la humildad y la preparación. El inversionista humilde dice: no sé qué va a pasar, así que actuaré con paciencia, aprenderé lo que pueda y no arriesgaré más de lo que puedo permitirme perder.",
        "Puedes someter cualquier oportunidad a unas cuantas señales de alerta. ¿Promete rendimientos inusualmente altos con poco o ningún riesgo? ¿Es urgente, presionándote a decidir antes de poder pensar o consultar a alguien? ¿Es complicada de una manera que nadie te explica con sencillez? ¿Depende de reclutar a otras personas? Cualquiera de estas debería frenarte. Frenar cuesta casi nada. Apresurarse le ha costado mucho a la gente.",
      ],
    },
    {
      title: "Invertir en ti mismo",
      body: [
        "Antes de cualquier conversación sobre fondos o cuentas, las Escrituras señalan una inversión que va primero y que rinde por más tiempo: la que haces en ti mismo. Cuando Dios le dio a Bezaleel la habilidad para construir el tabernáculo, el texto no dice que Bezaleel la ganó solo con esfuerzo. Dice que Dios lo llenó de sabiduría, inteligencia y conocimiento en toda clase de obra. El don fue dado. Lo que Bezaleel hizo después fue la mayordomía: aplicarlo, afilarlo, ponerlo en uso. Tus capacidades, tu llamado y la forma particular del trabajo para el que Dios te hizo son activos y, como cualquier activo confiado a un mayordomo, pueden enterrarse en la tierra o ponerse a trabajar.",
        "Poner un don a trabajar rara vez ocurre por accidente. Pablo le dice a Timoteo que no deje su don sin usar sino que lo avive hasta convertirlo en llama. Avivar una llama requiere un esfuerzo continuo: un curso que afile una habilidad, una certificación que abra una puerta, un libro que cambie tu forma de pensar, una temporada de consejería o mentoría que despeje lo que te ha estado frenando. Nada de esto son lujos. Son el mantenimiento que un don requiere si va a seguir produciendo algo. Una herramienta que nunca se afila todavía corta, pero más lento y peor cada vez.",
        "La mentoría merece una mención aparte, porque las Escrituras la tratan como una de las maneras ordinarias en que ocurre el crecimiento. El hierro con hierro se aguza, y los sabios crecen en sabiduría al ser enseñados. Casi nadie se vuelve hábil, sabio o listo para un llamado en aislamiento. Detrás de la mayoría de las personas competentes hay alguien que las enseñó, las corrigió o simplemente les mostró el camino por el tiempo suficiente como para que se les pegara. Buscar un mentor, pagar buena instrucción o invertir tiempo en un programa creado por personas más adelantadas que tú no es un atajo para saltarse el crecimiento. Es uno de los caminos más ordinarios hacia él.",
        "Esto no es un llamado a gastar sin límite en superación personal, y no está separado de la disciplina que enseña el resto de este curso. Un curso, un libro o una hora con un mentor todavía compite con tus otras fuentes, tus ahorros y tu generosidad, y debe sopesarse con la misma honestidad. Pero rara vez se desperdicia un dólar que afila la misma capacidad que produce tus otros dólares. Fuiste creado para buenas obras que Dios preparó de antemano para que anduvieras en ellas. Invertir en ti mismo es simplemente tomarlo lo bastante en serio como para crecer hacia eso.",
      ],
    },
    {
      title: "Tiempo y paciencia",
      body: [
        "De todos los ingredientes de la inversión exitosa a largo plazo, el tiempo es el menos glamoroso y el más poderoso. Eclesiastés da una imagen que se ha llevado a incontables sermones: echa tu pan sobre las aguas, que después de muchos días lo hallarás. La imagen es de una acción que no da fruto de inmediato y que hay que sostener con confianza durante una demora. Invertir tiene la misma forma. Pones algo afuera y esperas.",
        "Jesús usó el mismo ritmo en una pequeña parábola sobre una semilla. Un hombre esparce semilla en la tierra, y luego duerme y se levanta, de noche y de día, y la semilla brota y crece sin que él sepa cómo. La tierra da fruto por sí misma, primero la hoja, luego la espiga, y después el grano maduro en la espiga. El punto no es que el agricultor no haga nada. Es que gran parte del crecimiento ocurre en el espacio entre la acción y el resultado, en un proceso que nadie controla.",
        "Santiago agrega el lado moral: sean pacientes, como el labrador que espera el fruto precioso de la tierra, siendo paciente en ello hasta que recibe la lluvia temprana y la tardía. Un agricultor no puede apurar la cosecha. Lo que sí puede hacer es preparar el terreno, sembrar a tiempo y mantener la fe durante la espera. Los inversionistas que les va bien durante largos períodos suelen ser los que resisten el impulso de reaccionar a cada titular.",
        "A menudo se ilustra con un poco de aritmética sencilla. Si una cantidad crece un cierto porcentaje al año, y luego el crecimiento mismo crece, el efecto a lo largo de décadas es mucho mayor que el efecto de unos pocos años. A esto a veces se le llama interés compuesto. Es una ilustración, no una predicción, pues los resultados reales varían y pueden ser negativos en un año dado. Pero la lección de fondo es sólida y coherente con las Escrituras: empezar antes, aportar con regularidad y mantener la paciencia suele importar más que encontrar el momento perfecto.",
      ],
    },
    {
      title: "Calcula el costo: sabe lo que tienes y por qué",
      body: [
        "Jesús ofreció una pieza de sabiduría cotidiana sobre planear: ¿quién de ustedes, queriendo construir una torre, no se sienta primero a calcular el costo, para ver si tiene lo suficiente para terminarla? Hablaba del discipulado, pero el ejemplo que escogió era financiero, y el principio se aplica directamente. Antes de comprometer dinero, entiende a qué lo estás comprometiendo.",
        "Proverbios hace un punto relacionado de tres maneras distintas. El simple todo lo cree, pero el avisado mira bien sus pasos. El afán sin conocimiento no es bueno, y el que se apresura con los pies peca. El entusiasmo no sustituye al entendimiento. Si no puedes explicar en pocas frases sencillas qué es una inversión, cómo gana dinero, qué podría hacerle perder dinero y cuánto te cuesta, probablemente no estás listo para poner dinero en ella.",
        "Los costos merecen una atención especial porque son seguros mientras que los rendimientos no lo son. Las comisiones y los gastos que se cobran dentro de una inversión reducen lo que te quedas, año tras año, y los porcentajes pequeños se componen con el tiempo igual que los rendimientos. Los impuestos también importan, y las reglas difieren según el tipo de cuenta y el lugar. Nada de esto quiere decir que el costo sea lo único que importa. Quiere decir que el costo es una de las pocas cosas que de verdad puedes observar de antemano.",
        "Puedes hacerle preguntas sencillas a cualquier cosa que estés considerando. ¿Qué es exactamente lo que estoy comprando? ¿Cómo gana dinero? ¿De cuántas maneras podría perder dinero? ¿Cuáles son las comisiones? ¿Qué tan fácil es sacar mi dinero si lo necesito, y a qué costo? ¿Quién se beneficia si digo que sí, y cómo le pagan? Un profesional honesto responderá esto con gusto. Si las respuestas son vagas o la persona se irrita, toma eso también como información.",
      ],
    },
    {
      title: "Repartir el riesgo",
      body: [
        "Conocimos el principio de repartir el esfuerzo en el primer río, y se aplica por lo menos con la misma fuerza aquí. Eclesiastés dice que dividas tu porción entre siete, o aun ocho, porque no sabes qué calamidad pueda venir sobre la tierra. En su lectura más sencilla es un consejo antiguo contra poner todo en un solo lugar. Si una sola empresa fracasa, una persona que repartió sus recursos sobrevive, mientras que una persona que apostó todo a ella no.",
        "La inversión moderna tiene un nombre para la idea: diversificación. Significa tener una variedad de cosas que no suben y bajan todas juntas, de modo que ninguna decepción sea fatal. No elimina el riesgo, ni garantiza una ganancia. Su propósito es más modesto y más importante: evitar que un solo error, o un solo suceso desafortunado, te arruine. Una persona que tiene mucho de una sola empresa, incluida la empresa que la emplea, está expuesta de una manera fácil de pasar por alto hasta que duele.",
        "Las Escrituras dan dos advertencias para mantener esto en proporción. Proverbios dice que el que confía en sus riquezas caerá, pero los justos reverdecerán como el follaje. El salmista dice que si las riquezas aumentan, no pongamos el corazón en ellas. Estos versículos no nos dicen que evitemos invertir. Nos dicen dónde poner nuestra confianza. Una cartera bien armada es una herramienta, no un salvador. Si una caída del mercado destruyera tu paz o tu fe, parte de la confianza se ha desplazado al lugar equivocado.",
        "Una manera práctica de sostener ambas verdades es invertir solo lo que no necesitarás pronto, y solo después de tener tu reserva de emergencia. El dinero que podrías necesitar en pocos años pertenece a algo estable, no a algo cuyo valor puede oscilar mucho. El dinero de más largo plazo puede tolerar más movimiento, porque hay tiempo para recuperarse. El equilibrio correcto depende de tus metas, de tu horizonte de tiempo y de tu temperamento, y un profesional con licencia puede ayudarte a pensarlo.",
      ],
    },
    {
      title: "Ganancia honesta",
      body: [
        "Un enfoque cristiano de la inversión tiene que preguntar no solo si una ganancia es posible sino si es honesta. Proverbios dice que el peso falso es abominación al Señor, pero la pesa cabal le agrada. La imagen es la de un comerciante con balanzas manipuladas. En términos modernos, la pregunta es si la manera de obtener un rendimiento implica engañar, defraudar o explotar a otra persona. Una ganancia obtenida dañando a las personas no es neutral.",
        "Otro proverbio dice que los tesoros mal habidos no sirven de nada, pero la justicia libra de la muerte. Y un tercero dice que mejor es lo poco con justicia que la muchedumbre de frutos sin derecho. Estos no apuntan a una clase de activo específica. Son un recordatorio de que el origen de un rendimiento importa. Dos números idénticos en un estado de cuenta pueden venir de lugares muy distintos, y Dios nota la diferencia.",
        "Esto no significa que siempre puedas saber todo sobre cada empresa o fondo. El mundo es complicado, y nadie tiene una cartera perfectamente limpia. Pero sí significa que puedes llevar tus valores a la mesa. Puedes preguntar qué hace realmente un negocio y si te sientes cómodo con eso. Puedes preferir inversiones que produzcan algo útil. Puedes evitar arreglos que dependan del engaño. Muchas personas descubren que esto hace que invertir se sienta menos como un juego de números desapegado y más como parte de su discipulado.",
        "También afecta cómo tratas a otras personas en los tratos financieros. Si prestas, inviertes con amigos o te asocias en un negocio, sé claro, sé justo y pon los acuerdos por escrito. Los apretones de manos son hermosos, pero las memorias difieren. Los daños financieros más comunes en las iglesias y las familias no vienen de villanos. Vienen de arreglos vagos entre personas que confiaban unas en otras.",
      ],
    },
    {
      title: "Consejo, humildad y los límites de este curso",
      body: [
        "Proverbios vuelve una y otra vez al valor del consejo. Los planes se frustran sin consulta, pero con muchos consejeros triunfan. El camino del necio es derecho en su opinión, pero el que obedece al consejo es sabio. Donde no hay dirección el pueblo cae, pero en la abundancia de consejeros hay seguridad. Este curso ha enseñado principios. No puede conocer tus ingresos, tus deudas, tus dependientes, tus metas, tu situación fiscal ni tu temperamento. Un profesional con licencia y de confianza sí puede.",
        "Cuando busques uno, ten el mismo cuidado que aconsejaría Proverbios. Pregunta cómo le pagan y si está legalmente obligado a actuar en tu interés. Pregunta qué recomendaría y por qué, y cuáles son los riesgos. Desconfía de cualquiera que garantice resultados, te presione a actuar rápido o no quiera poner las cosas por escrito. Y sigue conversando con un cónyuge, un mentor o un amigo sabio que no esté vendiendo nada.",
        "Santiago añade una última nota de humildad que le sienta bien a todo inversionista. Habla de personas que dicen que hoy o mañana irán a tal ciudad, pasarán allá un año, harán negocio y tendrán ganancia, sin saber lo que traerá el mañana. Su vida, dice, es un vapor que aparece por un poco de tiempo y luego se desvanece. Más bien, deberían decir: si el Señor quiere, viviremos y haremos esto o aquello. No es una razón para dejar de planear. Es un recordatorio de planear sin arrogancia.",
        "Los mejores inversionistas, al final, son los que sostienen sus planes con soltura. Aportan con regularidad, entienden lo que poseen, reparten su riesgo, buscan consejo y aceptan que el futuro no les toca controlarlo. Esa postura no es solo buena práctica financiera. Es buena práctica espiritual, y es notablemente tranquilizadora.",
      ],
    },
    {
      title: "La práctica: anota una aportación",
      body: [
        "Tu práctica para el tercer río es anotar una aportación de inversión. Puede ser algo que ya hiciste, como una aportación de retiro descontada de tu sueldo, o algo que planeas hacer este mes. No hay mínimo ni respuesta equivocada. Si todavía no inviertes nada, este puede ser el momento de pensar por qué y de anotar qué tendría que ser cierto para que empieces. No todo hogar debería invertir ahora mismo. Algunos deberían estar construyendo un colchón de emergencia o reduciendo deuda costosa primero, y eso es sabio, no débil.",
        "Anota a qué va la aportación, como una cuenta de retiro o un fondo, y luego usa un monto rápido o uno personalizado para registrar lo que pusiste. Agrega una nota a tu yo del futuro sobre el porqué, si quieres. Este registro es sencillo a propósito. Anota lo que aportaste y cuándo. No muestra el valor actual de nada, no trae precios del mercado y no te dice si una inversión es buena o mala. La razón es deliberada: tu trabajo en esta etapa es construir el hábito de la aportación fiel, no mirar cómo se mueven los números.",
        "Con el tiempo, el registro se convierte en un silencioso testimonio de paciencia. Puedes mirar atrás y ver que seguiste presentándote, mes tras mes, en buenos mercados y en malos. Ese registro vale más que el saldo de un solo día. También es algo útil para llevar a un asesor con licencia, que querrá saber lo que realmente has estado haciendo.",
        "Al terminar, considera algunas preguntas. ¿Estoy enterrando, apostando o administrando? ¿A qué le tengo miedo y de qué estoy demasiado seguro? ¿Entiendo lo que poseo y lo que cuesta? ¿Quién es una persona sabia con quien podría hablar de esto? ¿Y qué haría distinto si de verdad creyera que estos recursos le pertenecen a Dios y yo los estoy administrando por un tiempo? Cuando hayas leído la lección y anotado una entrada, el tercer río estará completo y se abrirá el cuarto.",
      ],
    },
  ],
};
