import type { RiverText } from "./types";

/** Spanish text of River 2. The verses stay in content/lessons/river2.ts. */
export const RIVER2_TEXT: RiverText = {
  title: "Ahorro",
  intro:
    "Un río del que solo se saca agua termina secándose, y un río al que nunca se le retiene nada se desborda y luego desaparece. El segundo río del curso trata del sabio punto medio: retener una parte de lo que entra, a propósito, antes de gastarla. Ahorrar es una de las prácticas espirituales menos glamorosas, y una de las más constantemente elogiadas en las Escrituras. En esta lección veremos por qué importa una reserva, en qué se diferencia ahorrar de acaparar, cómo darle a tu ahorro un nombre y un plan, por qué lo pequeño y regular supera a lo grande y ocasional, cómo prepararte para las temporadas difíciles y para las personas que dependen de ti, y cómo la deuda y el descontento vacían en silencio la reserva. Al final establecerás una meta de ahorro y anotarás una primera aportación hacia ella.",
  practicePrompt: "Crea una meta de ahorro y anota tu primera aportación hacia ella.",
  lessons: [
    {
      title: "Por qué un río necesita una reserva",
      body: [
        "Imagina un pueblo construido junto a un río que fluye con generosidad en primavera y se reduce a un hilo a finales del verano. El pueblo sabio construye un embalse. En la temporada de abundancia recoge y retiene agua, y en la temporada de escasez la libera. El embalse no hace más grande el río. Cambia cuándo está disponible el agua. Eso es exactamente lo que hace el ahorro con el dinero. Traslada una parte de la abundancia de una buena temporada a una difícil, para que esa difícil no tenga que sobrevivirse con un hilo.",
        "La imagen bíblica más clara de esto es José en Egipto. Faraón soñó con siete años gordos seguidos de siete flacos, y José aconsejó juntar la comida de los años buenos y guardarla en las ciudades, para que la tierra no pereciera con el hambre. Fíjate que José no predijo el hambre por ser hábil en economía. Se le dijo lo que venía. A la mayoría de nosotros no se nos dice. Pero sabemos por la vida ordinaria que las temporadas flacas sí llegan: una cuenta médica, un auto que muere, un empleo perdido, un año lento en el negocio. Simplemente no sabemos cuándo.",
        "La hormiga aparece en Proverbios como maestra por esa misma razón. Se la describe como una criatura sin fuerza, y sin embargo prepara su comida en el verano. La lección no es que las hormigas sean pensadoras sabias. Es que prepararse no requiere gran fuerza ni gran ingreso. Requiere el hábito de apartar algo mientras la temporada es amable. Proverbios también dice que en la casa del sabio hay tesoro precioso, pero que el necio todo lo disipa. La diferencia entre los dos no es lo que ganan. Es lo que guardan.",
        "Vale la pena decir esto con claridad porque mucha gente supone que ahorrar es solo para quienes les sobra mucho. En la práctica, lo contrario se acerca más a la verdad. Quienes tienen poco margen son quienes más pierden con una sola sorpresa, y por eso tienen la razón más fuerte para empezar, aunque el comienzo sea pequeño.",
      ],
    },
    {
      title: "Ahorrar no es acaparar",
      body: [
        "Toda enseñanza honesta sobre el ahorro tiene que enfrentar las advertencias que Jesús dio sobre la riqueza, porque es fácil oír elogios al ahorro y deslizarse hacia algo que Jesús condenó. En una ocasión, un hombre de la multitud le pidió a Jesús que resolviera una disputa de herencia. Jesús respondió diciéndoles a todos que se cuidaran y se guardaran de toda avaricia, porque la vida de una persona no consiste en la abundancia de sus bienes. Luego contó una historia.",
        "En la historia, un agricultor tiene una cosecha extraordinaria. Decide derribar sus graneros y construir otros más grandes, y luego decirse a sí mismo que descanse, coma, beba y se alegre. Dios lo llama necio, porque esa misma noche le pedirían su vida, y todo lo que había almacenado sería de otro. La historia termina con una línea que vale la pena memorizar: así es el que hace para sí tesoro y no es rico para con Dios.",
        "¿Qué estaba mal en el agricultor? No era que almacenara grano. José almacenó grano, y eso fue sabio. El problema era que el almacenamiento era enteramente para sí mismo, el plan no tenía lugar para Dios ni para el prójimo, y la seguridad que estaba comprando era falsa, de las que dicen mi vida está a salvo porque mis graneros están llenos. En el Sermón del Monte, Jesús hace el mismo punto desde otro ángulo: no acumulen tesoros en la tierra, donde la polilla y la herrumbre destruyen, sino acumulen tesoros en el cielo, porque donde esté su tesoro, allí estará también su corazón.",
        "Entonces, ¿cómo distinguimos el ahorro del acaparamiento? Algunas señales ayudan. El ahorro tiene un propósito: apunta a una necesidad, una meta o un llamado. El acaparamiento no tiene más destino que más. El ahorro es compatible con la generosidad, y a menudo la hace posible. El acaparamiento aprieta el puño cuando alguien necesita ayuda. El ahorro te deja dormir. El acaparamiento te exige que sigas revisando. Si tus ahorros te hacen más libre, más generoso y más tranquilo, están haciendo su trabajo. Si te hacen más ansioso, más a la defensiva y más resentido ante las peticiones, mira de nuevo tu corazón.",
      ],
    },
    {
      title: "Ponle nombre a la meta, planea el trabajo",
      body: [
        "El dinero sin destino tiende a encontrar uno. Esa es la verdad poco glamorosa detrás de la mayoría de los intentos fallidos de ahorrar. La gente decide ahorrar lo que sobre a fin de mes, y a fin de mes no sobra nada, porque un mes es muy bueno para gastar todo lo que se le da. El remedio es ponerle nombre y número al ahorro antes de que empiece el mes.",
        "Una buena meta de ahorro responde tres preguntas. ¿Para qué es? ¿Cuánto necesito? ¿Para cuándo? Un fondo de emergencia puede ser un colchón de tres a seis meses de gastos esenciales. Un vehículo de reemplazo puede ser una cantidad específica para un año específico. Una primera casa, un viaje familiar, una boda, unos estudios o un compromiso con el ministerio se vuelven concretos cuando los escribes. El nombre importa emocionalmente. Es mucho más fácil hacer un pequeño sacrificio por el techo nuevo que por la idea abstracta de ser responsable.",
        "Proverbios dice que los planes del diligente ciertamente tienden a la abundancia, pero todo el que se apresura llega solo a la pobreza. Otro proverbio da un orden de operaciones para un agricultor: ordena tus labores de fuera y tenlas listas en el campo, y después edifica tu casa. El principio es que el cimiento viene antes del acabado. En términos del hogar, la reserva viene antes de los lujos, y el plan viene antes de la compra. Ahorrar es el trabajo de campo de una vida financiera. No es emocionante, pero la casa depende de él.",
        "Así puede verse una meta con nombre en la práctica. En lugar de una intención vaga de juntar algún ahorro, un hogar escribe: un colchón inicial de emergencia de mil dólares, para fines de marzo, a veinticinco dólares por semana. Fíjate que la oración contiene un propósito, un monto, una fecha y un ritmo. Cualquiera que la lea puede saber de un vistazo si va por buen camino. Una meta así también te da un momento natural de celebración, que importa más de lo que parece. La gente mantiene los hábitos que se le permite disfrutar al terminar.",
        "También ayuda ordenar tus metas en secuencia en lugar de perseguirlas todas a la vez. Muchas personas encuentran sabio construir primero un pequeño colchón inicial, luego atender cualquier deuda de alto costo, luego completar el colchón a su tamaño total y después perseguir metas más largas como un enganche o los estudios. La secuencia exacta depende de tu situación, y este curso no es asesoría personal. El punto es que las metas funcionan mejor en orden que en desorden.",
      ],
    },
    {
      title: "Poco a poco",
      body: [
        "Uno de los versículos más alentadores de Proverbios para cualquiera que se sienta atrasado es este: el dinero mal habido pronto se acaba, pero quien ahorra, poco a poco se enriquece. La frase poco a poco es todo el secreto del ahorro ordinario. La riqueza que dura rara vez se construye con golpes de suerte dramáticos. Se construye con actos pequeños y regulares, repetidos durante mucho tiempo, tanto que dejan de sentirse como sacrificios y empiezan a sentirse como hábitos.",
        "El profeta Zacarías hizo una pregunta que encaja aquí: ¿quién ha menospreciado el día de las pequeñeces? Es una suave reprensión al instinto que dice que una contribución pequeña no vale la pena. Un depósito modesto no parece mucho el día que lo haces. Pero hace tres cosas que un depósito grande y ocasional no puede. Construye el hábito. Mantiene la meta frente a ti. Y sobrevive a los cambios de ánimo, porque se decidió de antemano en lugar de sentirse en el momento.",
        "Pablo le dio a la iglesia de Corinto un ritmo práctico para apartar dinero. El primer día de cada semana, cada uno debía poner algo aparte y guardarlo según hubiera prosperado, para que no tuvieran que hacerse colectas a toda prisa cuando él llegara. Dos rasgos destacan. Era regular, semanal y no esporádico. Y era proporcional, según cómo hubieran prosperado, no una cantidad fija que ignorara sus circunstancias.",
        "¿Y si de verdad casi no sobra nada cada mes? Esta es una situación real para muchas personas fieles y trabajadoras, y merece una respuesta real y no un eslogan. Empieza más pequeño de lo que se siente respetable. Unos pocos dólares a la semana no son una broma. Construyen el hábito, te demuestran que la práctica es posible y te dan algo que hacer crecer cuando mejoren las circunstancias. Luego busca un lugar honesto donde aflojar la presión, ya sea en los ingresos, en los gastos o en ambos. El progreso a este nivel se mide en dirección, no en tamaño. Una persona que ahorra cinco dólares a la semana va más adelante que una persona que no ahorra nada y piensa ahorrar mucho.",
        "Hay un viejo consejo que vale la pena tomar prestado aquí: págate a ti primero. Si esperas hasta fin de mes para ver qué sobró, tu ahorro siempre será una ocurrencia tardía. Si mueves una cantidad fija a tu meta en el momento en que llega el ingreso, ahorrar se vuelve una decisión que tomaste una vez, en lugar de una decisión que debes ganar cada día. Muchas personas lo automatizan. Lo hagas o no, escoge una cantidad lo bastante pequeña como para que de verdad la cumplas, y deja que crezca a medida que crece tu capacidad.",
      ],
    },
    {
      title: "Para la temporada difícil y para quienes dependen de ti",
      body: [
        "Proverbios observa que el avisado ve el mal y se esconde, mientras que los simples siguen adelante y sufren el daño. El punto no es que los prudentes sean pesimistas. Es que responden al riesgo visible mientras todavía hay tiempo. Casi todo hogar enfrenta algunos riesgos visibles de antemano: un auto que envejece, una condición de salud, un empleo en una industria con problemas, una casa con un techo cansado. Un fondo de emergencia es la forma práctica de refugiarse. Es un cuarto que construyes antes de la tormenta.",
        "El salmista da una promesa alentadora en esta dirección. El Señor conoce los días de los íntegros, y su herencia será perpetua. No serán avergonzados en el tiempo malo, y en días de hambre se saciarán. No es una promesa de que las personas fieles nunca enfrentan dificultades. Es una promesa de que Dios las sostiene en ellas. El ahorro es una de las maneras en que a menudo lo hace. Cuando construyes una reserva, estás cooperando con la manera en que él provee.",
        "El ahorro también tiene un lado relacional. Pablo escribe que el que no provee para los suyos, y sobre todo para los de su propia casa, ha negado la fe. Es una frase fuerte, y debe leerse con cuidado. No está dirigida a las personas pobres o desafortunadas. Está dirigida a quienes podrían proveer y no quieren. Para los padres, los cónyuges y los hijos adultos de padres mayores, los ahorros suelen ser la forma concreta del amor. Son lo que le permite a una familia absorber un golpe sin desmoronarse.",
        "Proverbios va más allá y dice que el hombre de bien deja herencia a los hijos de sus hijos. Para la mayoría de las familias esa herencia será modesta, y no tiene que medirse solo en dinero. Pero el instinto detrás de ella es sano: pensar una generación adelante, dejar a quienes te siguen mejor preparados de lo que tú estabas. Incluso un pequeño hábito de ahorro, transmitido con el ejemplo, es una forma de herencia. Los hijos que ven a sus padres ahorrar con paciencia suelen aprender algo que ninguna charla podría enseñar.",
      ],
    },
    {
      title: "Deuda, contentamiento y el enemigo del ahorro",
      body: [
        "Si ahorrar es llenar una reserva, la deuda es un agujero en su fondo. Proverbios lo dice con claridad: el rico se enseñorea de los pobres, y el que toma prestado es siervo del que presta. Pablo dice: no deban a nadie nada, sino el amarse unos a otros. Estos versículos no son una prohibición general de toda clase de préstamos, y los cristianos reflexivos no están de acuerdo sobre dónde caen los límites. Pero describen un patrón real. La deuda reduce la libertad. Compromete una parte del ingreso de mañana con las compras de ayer, y hace más difícil dar, ahorrar o decirle que no a un mal trabajo.",
        "Por esa razón, casi toda enseñanza práctica sobre el ahorro incluye algún plan para la deuda. La deuda de consumo con intereses altos en particular tiende a anular el beneficio de ahorrar, porque el interés que pagas muchas veces supera lo que tus ahorros podrían ganar. Muchas personas encuentran sabio construir primero un pequeño colchón de emergencia, para que una sorpresa no las empuje de nuevo a pedir prestado, y luego pagar con enfoque la deuda costosa mientras siguen ahorrando algo. El orden y las cantidades dependen de tus circunstancias, y un profesional de confianza y con licencia puede ayudarte a sopesarlos.",
        "Debajo de la mecánica hay un tema espiritual: el contentamiento. Pablo escribió a los filipenses que había aprendido a contentarse, cualquiera que fuera su situación. Fíjate en la palabra aprendido. El contentamiento no era su condición natural. Era una habilidad que adquirió, muchas veces por el camino difícil. Gran parte del gasto excesivo no lo mueve la necesidad sino la comparación, un sentimiento silencioso de que estamos atrasados y que una compra nos pondrá al día. Contentarse no significa que nunca disfrutemos las cosas ni mejoremos nuestra vida. Significa que nuestra idea de lo suficiente no sube cada vez que sube nuestro ingreso.",
        "Una forma práctica de hacerlo crecer es esperar. A cualquier compra no esencial por encima de cierto monto, dale un período de enfriamiento de unos días. Muchos deseos se evaporan solos. Los que sobreviven suelen ser los que valen la pena considerar. Cada vez que esperas y no gastas, haces un pequeño depósito en la reserva y practicas el arte de lo suficiente.",
      ],
    },
    {
      title: "La práctica: fija una meta y haz el primer depósito",
      body: [
        "Tu práctica para el segundo río es establecer una meta de ahorro y anotar una primera aportación hacia ella. Elige algo específico y significativo, aunque sea pequeño. Si no sabes por dónde empezar, un fondo de emergencia es una primera meta sensata para muchos hogares, y una meta inicial modesta, como un mes de gastos esenciales, intimida mucho menos que una grande. Ponle nombre a la meta, dale un monto objetivo y luego usa los botones rápidos o el campo personalizado para anotar tu primer depósito.",
        "El registro anota cada aportación como una entrada propia, y tu saldo acumulado es siempre la suma de esas entradas. Nada se supone y nada se estima, lo que significa que el número que ves es una imagen verdadera de lo que realmente has apartado. Si te equivocas, puedes eliminar una entrada y el saldo se corregirá solo. El hábito que estás construyendo no es la perfección. Es la honestidad con un número pequeño, repetida.",
        "El botón rápido está pensado para un ritmo. Si ahorras la misma cantidad cada semana o cada día de pago, toca el más de esa cantidad cada vez. Con el paso de unos meses, el conteo a su lado se convierte en un registro silencioso de tu fidelidad. La instrucción de Pablo de apartar algo el primer día de cada semana es el ancestro de esta idea. La regularidad es el punto.",
        "Al terminar, considera algunas preguntas. ¿Para qué es realmente esta meta, debajo del número? ¿A quién protege? ¿Cuál es la cantidad más pequeña a la que podría comprometerme y que de verdad cumpliría? ¿Cuál es el hábito o gasto que más a menudo se come mi ahorro, y cómo se vería soltar su dominio? Escribe tus respuestas si eso te ayuda. La mano negligente empobrece, dice Proverbios, pero la mano de los diligentes enriquece. La diligencia aquí no significa intensidad. Significa presentarse, de maneras pequeñas, durante mucho tiempo. Cuando hayas leído esta lección y anotado una aportación, el segundo río estará completo y se abrirá el tercero.",
      ],
    },
  ],
};
