import type { RiverText } from "./types";

/** Spanish text of River 4. The verses stay in content/lessons/river4.ts. */
export const RIVER4_TEXT: RiverText = {
  title: "Generosidad",
  intro:
    "En el Edén, el río que regaba el huerto no se quedó allí. Se dividió, y las cuatro corrientes fluyeron hacia afuera, hacia el mundo más amplio. El cuarto río de este curso es hacia donde ha estado apuntando la mayordomía desde el principio: soltar una parte de lo que ha entrado, de manera deliberada y con alegría, para el bien de otras personas y la obra de Dios. Dar no es el precio de entrada a una buena vida, y no es un impuesto para los ricos. Es lo que hace un río. En esta lección veremos por qué tiene sentido dar cuando todo ya le pertenece a Dios, qué son las primicias y el diezmo y cómo los han entendido los cristianos, por qué el corazón detrás de un regalo importa más que su tamaño, cómo cuidar de los pobres y de las personas cercanas, qué significa y qué no significa sembrar y cosechar, y cómo sostener la riqueza con las manos abiertas. Al final anotarás un regalo y comenzarás un registro de tu generosidad.",
  practicePrompt: "Anota un regalo que hayas dado recientemente, o uno al que te estás comprometiendo ahora.",
  lessons: [
    {
      title: "Todo ya es Suyo",
      body: [
        "Es natural pensar en el dar como una resta. Tengo algo, le entrego una parte a otra persona y ahora tengo menos. Las Escrituras nos invitan a verlo de otra manera, porque parten de una premisa distinta sobre la propiedad. Mía es la plata, y mío es el oro, dice el Señor de los ejércitos. De Jehová es la tierra y su plenitud. Si eso es cierto, entonces lo que llamamos nuestro dinero es un préstamo. Somos administradores de recursos que le pertenecen a otro, y la única pregunta real es qué querría nuestro Dueño que se hiciera con ellos.",
        "El rey David dio un hermoso ejemplo de esta actitud en la reunión para la construcción del templo. El pueblo había dado con generosidad y alegría, y David oró delante de todos. ¿Quién soy yo, preguntó, y quién es mi pueblo, para que pudiésemos ofrecer voluntariamente cosas semejantes? Luego dijo la frase que reorienta todo: todo es tuyo, y de lo recibido de tu mano te damos. En otras palabras, solo estamos devolviendo lo que desde el principio ya era suyo. Dar no es pagarle a Dios de nuestro suministro. Es devolver a su fuente una pequeña porción de su suministro.",
        "Pablo hace la misma pregunta de una forma más directa. ¿Qué tienes que no hayas recibido? Y si lo recibiste, ¿por qué te jactas como si no lo hubieras recibido? Es una pregunta que humilla, y va contra un instinto muy moderno de creer que nuestro ingreso es producto solo de nuestro propio esfuerzo. El esfuerzo importa, pero la salud, el talento, la oportunidad, la familia y el momento nos fueron dados. Ninguno de nosotros se ganó las condiciones que hicieron posible que ganáramos.",
      ],
    },
    {
      title: "Primicias: dar en orden",
      body: [
        "Uno de los patrones de generosidad más antiguos de la Biblia es la ofrenda de las primicias. En una sociedad agrícola, la primera porción de la cosecha se llevaba a Dios antes de comer o vender el resto. Era un acto de orden y de confianza. Al dar primero, el agricultor declaraba que Dios iba antes que sus propias necesidades, y confiaba en que el resto de la cosecha alcanzaría.",
        "Proverbios da el principio en el lenguaje de la riqueza: honra al Señor con tus riquezas y con las primicias de todos tus frutos, y tus graneros se llenarán a reventar. La promesa unida a ese versículo a veces se ha tratado como una garantía de retorno económico, una lectura que examinaremos con cuidado más adelante en esta lección. Por ahora, fíjate en la estructura. La honra va primero. El dar precede al gastar. Se coloca a la cabeza de la fila y no al final.",
        "Esta es una idea práctica tanto como espiritual. El dinero que se da al último suele resultar ser dinero que no se da en absoluto, porque a fin de mes no queda nada. El dinero que se da primero queda protegido de la tendencia natural de los gastos a expandirse hasta consumirlo todo. Una persona que decide de antemano qué porción dará, y la aparta cuando llega el ingreso, está haciendo exactamente lo que hacía el agricultor de las primicias.",
        "La Biblia también muestra una forma temprana de dar proporcional antes de la ley de Moisés. Después de una victoria militar, Abraham le dio la décima parte de todo a Melquisedec, el sacerdote del Dios Altísimo. La ley estableció después el diezmo, la décima parte del producto de la tierra, como perteneciente al Señor y santo para él. Estos pasajes son el trasfondo de lo que los cristianos han discutido desde entonces sobre cuánto dar y de qué manera, que es el tema de la siguiente sección.",
      ],
    },
    {
      title: "El diezmo: una pregunta que la gente hace",
      body: [
        "Casi toda conversación sobre dar llega tarde o temprano a una pregunta: ¿tiene un cristiano que diezmar? Este es un tema en el que personas reflexivas y fieles no están de acuerdo, y merece una descripción honesta y no un decreto seguro de sí mismo. Este curso no te dirá qué hacer. Expondrá lo que dicen las Escrituras y cómo las han leído los cristianos, para que puedas buscar a Dios y el consejo sabio por ti mismo.",
        "La palabra diezmo simplemente significa una décima parte. En la ley del Antiguo Testamento, el diezmo sostenía a los sacerdotes y levitas, proveía para las fiestas y cuidaba del pobre y del extranjero. Malaquías confrontó al pueblo por retener, diciéndoles que trajeran todo el diezmo al alfolí para que hubiera alimento en la casa de Dios, e invitándolos a ponerlo a prueba y ver si no les abriría las ventanas del cielo y derramaría bendición. Ese pasaje se cita a menudo en las iglesias, y refleja la seriedad con que Dios trató el dar entre su pueblo.",
        "En el Nuevo Testamento, el cuadro es más matizado. Jesús criticó a los escribas y fariseos, diciendo que pagaban el diezmo de la menta, del eneldo y del comino, pero descuidaban lo más importante de la ley: la justicia, la misericordia y la fidelidad. Luego agregó algo significativo: esto es lo que debían haber hecho, sin descuidar aquello. No abolió la práctica del diezmo, pero dejó claro que nunca podría sustituir a un corazón justo. En otros lugares, los apóstoles enfatizan la generosidad, la alegría y la proporción sin fijar un porcentaje.",
        "Como resultado, los cristianos tienden a caer en unos cuantos grupos. Algunos consideran el diezmo una norma permanente y dan el diez por ciento de sus ingresos a su iglesia local, con ofrendas adicionales además de eso. Otros lo ven como un patrón del Antiguo Testamento que apunta a un llamado más amplio del Nuevo Testamento a la generosidad, y tratan el diez por ciento como una referencia inicial útil y no como una regla. Otros más dan una proporción mayor a medida que crecen sus ingresos. Sea cual sea tu postura, la mayoría coincide en varios puntos. El dar debe ser intencional. Debe ser proporcional a lo que tienes. Y debe estar libre tanto del legalismo como de las excusas.",
      ],
    },
    {
      title: "El corazón detrás del regalo",
      body: [
        "Cualquiera que sea la cantidad que decidas dar, las Escrituras insisten en que el corazón detrás del regalo importa más que su tamaño. Pablo les dijo a los corintios que cada uno dé como propuso en su corazón, no con tristeza ni por necesidad, porque Dios ama al dador alegre. La palabra alegre en el original lleva la idea de hilaridad, de una alegría que se desborda. Dios no busca un cumplimiento a regañadientes. Busca a un dador que ha decidido de antemano y que da libremente.",
        "Jesús hizo el mismo punto con una escena memorable en el templo. Se sentó frente al arca de las ofrendas y observó a la gente echar su dinero. Muchos ricos echaban grandes sumas. Entonces llegó una viuda pobre y echó dos moneditas de cobre, que valían una fracción de centavo. Jesús llamó a sus discípulos y les dijo que esa viuda pobre había echado más que todos los que echaban. Los demás dieron de lo que les sobraba, pero ella, de su pobreza, echó todo lo que poseía, todo lo que tenía para vivir. Medido por la cantidad, su regalo era diminuto. Medido por el costo y la confianza, era el más grande del lugar.",
        "Jesús también enseñó sobre el motivo de dar. Cuando des limosna, dijo, que no sepa tu mano izquierda lo que hace tu derecha, para que tu limosna sea en secreto, y tu Padre, que ve en lo secreto, te recompensará. Es una advertencia contra dar como espectáculo, dar para ser admirado o para construir una reputación. No significa que nunca puedas hablar de dar, pues las Escrituras también nos animan a inspirarnos unos a otros. Significa que el motivo debe ser el amor y la obediencia, no el aplauso.",
      ],
    },
    {
      title: "Los pobres y el prójimo",
      body: [
        "La iglesia y sus ministerios son un canal para dar. Las Escrituras también señalan un segundo canal igual de importante: la generosidad directa hacia las personas necesitadas. La ley de Moisés estaba llena de disposiciones para los pobres. A los agricultores se les decía que dejaran sin cosechar los bordes de sus campos para el pobre y el extranjero. Las deudas debían perdonarse. Y el mandato en Deuteronomio es inconfundible: nunca faltarán pobres en la tierra, por eso te ordeno: con liberalidad abrirás tu mano a tu hermano, al necesitado y al pobre en tu tierra.",
        "El patrón continúa en Proverbios, donde la mujer fuerte es descrita como la que alarga su mano al pobre y extiende sus manos al menesteroso. Continúa en el Nuevo Testamento, donde Santiago hace una pregunta difícil. Si un hermano o una hermana no tienen ropa y carecen del sustento diario, y uno de ustedes les dice: vayan en paz, caliéntense y sáciense, pero no les dan lo necesario para su cuerpo, ¿de qué sirve? La compasión sola no alimenta a nadie. La fe, dice Santiago, se muestra por lo que hacemos.",
        "¿Cómo se da con sabiduría a los pobres? Se recomiendan comúnmente algunos principios. Empieza por los más cercanos a ti: la familia, los vecinos, los compañeros de trabajo, los hermanos de la iglesia, pues son las personas que es más probable que conozcas lo bastante bien como para ayudar bien. Considera dar de maneras que preserven la dignidad y fomenten la independencia cuando sea posible, como ayudar a alguien a pagar una cuenta específica, a conectar con un trabajo o a ponerse de pie otra vez. Apoya a organizaciones de buena reputación que hacen este trabajo a escala, y tómate un poco de tiempo para revisar cómo manejan el dinero.",
      ],
    },
    {
      title: "Sembrar y cosechar, y lo que no significa",
      body: [
        "La Biblia describe el dar a menudo con el lenguaje de la agricultura. Pablo dice que el que siembra escasamente, escasamente también segará, y el que siembra abundantemente, abundantemente también segará. Proverbios dice que hay quien reparte y le es añadido más, y hay quien retiene lo que es justo solo para venir a menos, y que el alma generosa será prosperada, y el que riega será también regado. Jesús dice: den, y se les dará, una medida buena, apretada, sacudida y rebosante.",
        "Estos pasajes son reales, y describen algo verdadero sobre cómo Dios se relaciona con las personas generosas. Pero también están entre los versículos más mal usados de la Biblia. Algunos predicadores los tratan como una fórmula: da esta cantidad y Dios te devolverá más. Esa lectura convierte un regalo en una transacción y a Dios en una máquina expendedora. También suele dañar a quienes menos pueden permitírselo, al empujarlos a dar lo que no pueden dar con la esperanza de un retorno que nunca llega.",
        "Una lectura más fiel presta atención a lo que es la cosecha. A veces es económica, y a veces no. A veces es gratitud, a veces libertad del dominio del dinero, a veces relaciones, a veces el gozo de ver a otros ayudados. Pablo, en el mismo pasaje, dice que Dios es poderoso para hacer que abunde en ustedes toda gracia, a fin de que, teniendo siempre todo lo suficiente en todas las cosas, abunden para toda buena obra. La promesa es de suficiencia para la generosidad, no de lujo ilimitado. La bendición está hecha para transmitirse.",
      ],
    },
    {
      title: "Sostener la riqueza con las manos abiertas",
      body: [
        "Pablo le dio a Timoteo una encomienda para los que eran ricos en aquel tiempo, que sirve como un cuadro apropiado de todo el curso. A los ricos de este mundo, mándales que no sean arrogantes ni pongan su esperanza en las riquezas, que son tan inseguras, sino en Dios, que nos provee de todo en abundancia para que lo disfrutemos. Que hagan el bien, que sean ricos en buenas obras, generosos y dispuestos a compartir lo que tienen. De este modo, atesorarán para sí un seguro fundamento para el futuro y obtendrán la vida verdadera.",
        "Fíjate en el equilibrio de esa encomienda. La riqueza no se trata como algo malo. Dios provee ricamente todo para nuestro disfrute, y el disfrute no es pecado. Pero la riqueza se trata como algo poco confiable, y la esperanza no debe anclarse en ella. Y la instrucción para los ricos no es sentir culpa sino ser ricos en buenas obras, generosos y dispuestos a compartir. La generosidad es lo que convierte la riqueza de una posesión en un recurso.",
        "Jesús expone el asunto de fondo en los términos más severos. Ninguno puede servir a dos señores, porque o aborrecerá al uno y amará al otro, o estimará al uno y menospreciará al otro. No pueden servir a Dios y a las riquezas. No es una advertencia de que el dinero sea malo. Es una advertencia sobre quién manda. A toda persona la sirve algo. El dinero es un excelente siervo y un terrible amo. Dar es una de las maneras más claras y prácticas de mantener bien el orden.",
        "Por eso el dar pertenece al final del curso, y por eso cambia cómo se siente todo lo anterior. Una persona que gana, ahorra e invierte sin dar puede convertirse poco a poco en alguien que custodia un montón. Una persona que hace las cuatro cosas se convierte en algo mejor: un canal. El agua entra, se retiene y se pone a trabajar, y luego fluye hacia otros. El huerto es regado, y también el mundo más allá de él.",
      ],
    },
    {
      title: "La práctica: planea tu generosidad y lleva un registro",
      body: [
        "Tu práctica para el cuarto río es anotar un regalo. Puede ser un regalo que ya diste recientemente o uno al que te estás comprometiendo ahora. Anota quién lo recibió y cuánto, y agrega una nota si hay algo que quieras recordar. Los botones rápidos facilitan registrar regalos repetidos, como una cantidad semanal o mensual a tu iglesia. Cada entrada es una fila real en tu registro, y tu total anual siempre es la suma de tus entradas.",
        "¿Por qué llevar un registro de lo que das? Puede sonar a contradicción de la instrucción de Jesús de que no sepa tu mano izquierda lo que hace tu derecha. Pero el registro es privado, y su propósito es la mayordomía, no el aplauso. Proverbios nos urge a conocer bien el estado de nuestras ovejas y a prestar atención a nuestros rebaños. Un registro te ayuda a ver si tu generosidad coincide con tus intenciones. Muestra si dar es un ritmo regular o un impulso ocasional, y te ayuda a planear en lugar de reaccionar.",
        "Considera hacer un plan sencillo. Decide, mientras oras y reflexionas, qué porción de tus ingresos quieres dar y a dónde. Considera dividirla entre tu iglesia local, otros ministerios u organizaciones en las que confías, y la ayuda directa a personas necesitadas que conoces. Decide en qué momento del mes lo darás, idealmente cerca del momento en que llega el ingreso, para que vaya primero y no al último. Y decide cómo responderás cuando aparezca una necesidad inesperada, para poder decir que sí sin andar corriendo.",
        "Al terminar, algunas preguntas pueden ayudar. ¿He dado alguna vez de una manera que se sintiera verdaderamente alegre? ¿Qué me ha estado frenando, ya sea el miedo, el hábito o la falta de un plan? ¿A quién en mi vida podría ayudar con algo que ya tengo? Y si confiara en que todo lo que tengo le pertenece a Dios, ¿qué cambiaría en mi manera de dar este año? Escribe tus respuestas si quieres. Al Señor presta el que da al pobre, dice Proverbios, y él le pagará su buena obra. Cuando hayas leído esta lección y anotado un regalo, el cuarto río estará completo, y el curso también. Se abrirá tu panel, donde podrás seguir llevando el registro de los cuatro ríos todo el tiempo que quieras.",
      ],
    },
  ],
};
