import type { RiverText } from "./types";

/** Spanish text of River 1. The verses stay in content/lessons/river1.ts. */
export const RIVER1_TEXT: RiverText = {
  title: "Múltiples fuentes de ingresos",
  intro:
    "Mucho antes de que existieran los cheques de sueldo, las facturas o los negocios propios, había un huerto y un río. El libro de Génesis dice que un río salía del Edén para regar el huerto, y que de allí se dividía y se convertía en cuatro. La imagen es sencilla y profunda a la vez. Hay una sola fuente, y aun así a la fuente no se le pide que viaje por un solo cauce. Alimenta muchos lugares a la vez. Este primer río del curso se toma esa imagen en serio. Veremos de dónde viene realmente el ingreso, por qué el trabajo es digno, por qué depender de una sola fuente es frágil, cómo son los distintos tipos de fuentes de ingresos y cómo ampliar tu provisión sin que se amplíe tu apetito. Léelo despacio, o deja que el lector lo diga en voz alta mientras caminas o manejas. Al final harás un inventario sencillo de las fuentes que ya tienes.",
  practicePrompt: "Anota cada fuente de ingresos que tienes hoy, una entrada por fuente.",
  lessons: [
    {
      title: "Una sola fuente, muchas corrientes",
      body: [
        "Empecemos con la afirmación más importante de todo este curso: la fuente de todo lo que ganarás nunca es tu empleador, tus clientes ni tu propio ingenio. Las Escrituras son consistentes en este punto. Moisés advirtió a un pueblo próspero que no dijera en su corazón que su propia fuerza y el poder de sus manos le habían dado la riqueza. En cambio, les dijo que se acordaran del Señor, porque es Dios quien da el poder para producir riqueza. Santiago describe toda buena dádiva y todo don perfecto como algo que desciende de lo alto. Si eso es cierto, entonces el ingreso no es principalmente algo que arrebatamos. Es algo que recibimos y luego administramos.",
        "Esto importa en la práctica, no solo en lo devocional. Las personas que creen ser la única fuente de su ingreso tienden a vivir en uno de dos estados de ánimo. El primero es la ansiedad, porque todo depende de ellas. El segundo es el orgullo, porque todo vino de ellas. Quienes se ven como mayordomos de un regalo tienden a vivir en un tercer estado, que es la gratitud con responsabilidad. Trabajan duro, porque los regalos están hechos para usarse, pero sostienen el resultado con soltura, porque el Dador no ha desaparecido.",
        "Así que cuando esta lección habla de construir múltiples fuentes de ingresos, no describe un esquema para hacerse rico. Describe la manera sabia de canalizar un suministro que nunca fue tuyo desde el principio. El río del Edén no se dividió porque el agua escaseara. Se dividió porque un huerto tiene muchos lugares que necesitan riego. Tu hogar, tu futuro, tu iglesia y tus vecinos son todos lugares que necesitan agua, y un solo cauce angosto rara vez llega a todos.",
        "Fíjate también en lo que la imagen deja fuera. Los cuatro ríos no compiten entre sí. Nadie en el Edén preguntó cuál era el mejor. Cada uno llevaba la misma agua a una región distinta, y cada región era regada gracias a eso. A medida que avanzamos, resiste la tentación de clasificar tus fuentes por prestigio. Una fuente modesta que corre con constancia vale mucho más que una impresionante que se seca en agosto.",
      ],
    },
    {
      title: "El trabajo es parte del diseño",
      body: [
        "Antes de hablar de agregar fuentes, conviene aclarar qué es el trabajo. Una suposición común es que el trabajo es una consecuencia de la caída, una especie de maldición que aguantamos hasta el fin de semana. Pero Génesis coloca el trabajo antes de la caída. Dios puso al hombre en el huerto para que lo cultivara y lo guardara. El trabajo era parte del diseño original, una manera de participar en el cuidado de la creación. Eso no significa que todo empleo sea agradable ni que todo lugar de trabajo sea justo. Significa que el acto básico de producir algo útil para otras personas es digno.",
        "Pablo lleva esto al Nuevo Testamento con dos instrucciones muy distintas. A los creyentes de Colosas, muchos de los cuales eran siervos con poco que decir sobre sus condiciones de trabajo, les escribió que todo lo que hicieran lo hicieran de buena gana, como para el Señor y no para las personas. A la iglesia de Tesalónica, donde algunos habían dejado de trabajar mientras esperaban un futuro dramático, les habló sin rodeos: si alguno no quiere trabajar, que tampoco coma. Juntos, estos dos pasajes sostienen dos verdades en tensión. Vale la pena hacer bien el trabajo, y la ociosidad no es una estrategia.",
        "¿Por qué empezar aquí? Porque toda fuente de ingresos, cualquiera sea su forma, se apoya en alguna clase de trabajo, aun cuando ese trabajo se haya hecho antes. Una propiedad en renta representa trabajo invertido al inicio y trabajo de cuidado continuo. Una regalía representa el trabajo de crear algo. Un dividendo representa capital que alguien tuvo que acumular con trabajo. Las múltiples fuentes no son una escapatoria del trabajo. Son una manera más sabia de organizarlo.",
        "Vale la pena revisar tu propia actitud en este punto. Si te acercas a la idea de ingresos extra con la fantasía de no volver a trabajar nunca, esta lección te va a decepcionar. Si te acercas con la pregunta de cómo administrar más plenamente tus capacidades, estás en el lugar correcto. La meta no es contribuir menos. La meta es contribuir de una manera más resistente.",
      ],
    },
    {
      title: "Por qué una sola fuente es frágil",
      body: [
        "Piensa en cuántos hogares dependen de una sola fuente de ingresos. Muchas familias lo eligen a propósito, y lo eligen bien: uno de los padres provee mientras el otro trabaja en casa criando a los hijos y atendiendo el hogar, un arreglo que muchos encuentran profundamente valioso. Lo que importa aquí es por cuántos cauces corre el ingreso, no quién lo gana ni cómo un hogar divide su trabajo. Una sola fuente funciona bien hasta el día en que deja de hacerlo: un despido, una enfermedad, una empresa que se muda, una industria que se encoge. En esos momentos un hogar descubre que en realidad nunca tuvo un ingreso, sino un único punto de falla. Todo, incluida la renta, la comida, la generosidad y el ahorro, fluía por un solo cauce angosto, y cuando el cauce se bloqueó, todo se detuvo a la vez.",
        "El escritor de Eclesiastés lo vio hace mucho tiempo. Aconsejaba dar una porción a siete, y aun a ocho, porque no sabes qué calamidad pueda venir sobre la tierra. Luego añadió una segunda imagen del campo: siembra tu semilla por la mañana y por la tarde no dejes descansar tu mano, porque no sabes si prosperará esta o aquella, o si ambas serán igualmente buenas. Esto no es una receta para la actividad frenética. Es una admisión honesta de la incertidumbre. No podemos predecir qué esfuerzo dará fruto, así que la sabiduría reparte el esfuerzo.",
        "Proverbios hace una observación parecida desde el otro lado. Las riquezas no duran para siempre, y ni siquiera una corona permanece de generación en generación. Sea como sea tu ingreso hoy, trátalo como una temporada y no como una garantía. Las temporadas cambian. Quien solo ha tenido un campo está a merced de un solo tipo de clima.",
        "Quizá ayude imaginar dos hogares con el mismo ingreso total. En el primero, todo llega como un solo cheque de un único empleador. En el segundo, el mismo total se compone de un trabajo principal, un pequeño negocio de temporada e intereses modestos. Ambos pueden estar organizados exactamente igual en casa, con un proveedor y un padre o madre criando a los hijos. Lo que difiere es el número de fuentes, no el número de personas que ganan. En un día normal se ven iguales. El día en que el empleador principal anuncia despidos, ya no. El segundo hogar pierde una fuente grande pero conserva dos más funcionando, lo que compra tiempo, opciones y una conversación más tranquila en la mesa de la cocina. Diversificar no evita las malas noticias. Cambia cómo aterrizan.",
        "Nada de esto es un llamado al miedo. Es un llamado a prepararse. Un agricultor que siembra varios tipos de cultivos no es pesimista sobre la cosecha. Es realista sobre el cielo. Prepararse así es en realidad una forma de paz, porque te permite enfrentar noticias inciertas con un plan en la mano en lugar de una creciente sensación de pánico.",
      ],
    },
    {
      title: "Los muchos tipos de fuentes",
      body: [
        "¿Qué cuenta realmente como una fuente? La prueba más sencilla es esta: una fuente es un origen distinto de dinero que podría seguir fluyendo, al menos por un tiempo, aunque otra fuente se detuviera. Con esa definición, la mayoría de las personas tiene más fuentes de las que cree, y hay varias familias amplias que vale la pena conocer. Esto es un recorrido por el panorama, no una recomendación sobre lo que deberías buscar.",
        "La primera familia es el ingreso por trabajo: sueldos, salarios, trabajo por horas, propinas y proyectos freelance. Se intercambian directamente por tu tiempo y tu habilidad. Suelen ser la fuente más grande y más confiable, y también la más ligada a tu presencia continua. La segunda familia es el ingreso de negocio, donde ofreces un producto o servicio a clientes y te quedas con lo que sobra después de los costos. El ingreso de negocio puede crecer más allá de tus propias horas, pero también conlleva riesgo y exige administración.",
        "La tercera familia es el ingreso por activos: la renta de una propiedad, el interés de los ahorros y los dividendos de la propiedad en empresas. Estas fuentes fluyen de algo que posees y no de algo que haces ese día, aunque por lo general todavía requieren atención, y siempre requieren que alguien haya acumulado antes el capital. La cuarta familia es el ingreso creativo o intelectual, como las regalías, las licencias y el pago por cosas que hiciste una vez y puedes vender repetidamente. Algunas personas también tienen fuentes ocasionales o de temporada, como un mercado de fiestas, un bono anual o trabajos eventuales.",
        "Una advertencia sobre el vocabulario. La gente suele llamar pasivos a los ingresos por activos y creativos, y es cierto que estas fuentes pueden fluir sin que estés presente en una tarde determinada. Pero casi ninguna es sin esfuerzo. Una propiedad en renta necesita reparaciones e inquilinos. Una obra creativa tiene que terminarse antes de poder venderse, y a menudo necesita promoción después. Las inversiones necesitan paciencia y atención periódica. Piensa en estas fuentes como trabajo con otra forma, no como ausencia de trabajo. Esa manera de verlo te protege de la decepción y de cualquiera que prometa ingresos sin esfuerzo.",
        "Las Escrituras nos dan vistazos de personas con más de un cauce. La mujer descrita en Proverbios 31 considera un campo y lo compra, planta una viña con sus ganancias y hace telas finas y las vende a los mercaderes. Tiene tierra, agricultura y comercio funcionando a la vez. Pablo, en medio de la plantación de iglesias, trabajó haciendo tiendas con Aquila y Priscila para no ser una carga a quienes servía. Lidia, una creyente en Filipos, es presentada como vendedora de púrpura. En todos los casos, la fuente adicional no es una distracción del llamado. Es lo que hizo sostenible el llamado.",
      ],
    },
    {
      title: "Límites: diligencia sin codicia",
      body: [
        "Aquí tenemos que ir más despacio, porque el mismo instinto que lleva a una diversificación sabia también puede llevar a un hambre malsana. Las Escrituras no se andan con rodeos. Proverbios dice que el hombre fiel tendrá muchas bendiciones, pero que el que se apresura a enriquecerse no quedará sin castigo. Pablo escribe que los que quieren enriquecerse caen en tentación y lazo, y que el amor al dinero es raíz de todos los males. Fíjate en las palabras. El problema no es el dinero, y ni siquiera es la riqueza. El problema es el amor y la prisa.",
        "¿Cómo distingues la diferencia en ti mismo? Unas preguntas honestas ayudan. ¿Estoy agregando esta fuente para cubrir necesidades reales y tener algo que compartir, o la estoy agregando porque no soporto sentir que tengo suficiente? ¿Cada nueva fuente de ingresos eleva mi nivel de vida tan rápido que nunca soy más libre? ¿Estoy dispuesto a decirle que no a una oportunidad que dañaría a mi familia, mi salud o mi integridad, aunque pagara bien? Si una fuente me exige faltar a la honestidad, no es una fuente. Es una fuga.",
        "La carta a los Hebreos ofrece un antídoto constante: mantén tu vida libre del amor al dinero y conténtate con lo que tienes, porque Dios ha prometido nunca dejarte ni desampararte. El contentamiento no es lo mismo que la pasividad. Una persona puede estar contenta y aun así trabajar con diligencia, planear con cuidado y construir con sabiduría. Lo que el contentamiento quita es la creencia de que el próximo aumento por fin te hará sentir seguro. Esa creencia nunca ha sido cierta para nadie.",
        "Una regla útil es dejar que el propósito fije el tamaño. Si sabes para qué quieres más provisión, ya sea para construir un colchón, cuidar de padres mayores, tener libertad para dar o sostener un ministerio, el propósito te dice cuándo la fuente ya cumplió su trabajo. Sin propósito no hay meta, y una carrera sin meta es agotadora.",
      ],
    },
    {
      title: "Descanso, margen y los límites del ajetreo",
      body: [
        "Los consejos modernos sobre ingresos extra suelen sonar como una exigencia de producción constante: levántate más temprano, duerme menos, apila más proyectos. Las Escrituras ofrecen un ritmo muy distinto. El mandamiento del sábado dice que trabajarás seis días y harás toda tu obra, y que el séptimo día es reposo para el Señor. El descanso no es lo que hacemos cuando el trabajo termina. El descanso es parte del patrón que hace sostenible el trabajo, y un acto de confianza en que el mundo seguirá girando mientras nos detenemos.",
        "El salmista lo dice en términos memorables: es en vano que se levanten de madrugada y se acuesten tarde, que coman el pan de afanosa labor, pues Dios da sueño a los que ama. Esto no es una licencia para la pereza. Es una advertencia contra la clase de esfuerzo que trata cada hora como un recurso que hay que exprimir y cada descanso como una pérdida. Y Eclesiastés agrega una medida práctica: mejor un puñado con tranquilidad que dos puñados con fatiga y correr tras el viento.",
        "Esto tiene implicaciones directas en cómo construyes fuentes adicionales. Toda nueva fuente de ingresos cuesta atención, energía y tiempo con las personas que amas. Si una nueva fuente te deja con dos puñados y sin paz, quizá hayas sumado ingresos restando vida. Antes de asumir algo nuevo, pregunta qué desplazará. Pregunta qué dirían tu cónyuge, tus hijos o tus amigos más cercanos sobre el ritmo que llevas. Sus respuestas son datos.",
        "Muchas veces es más sabio construir despacio. Una fuente pequeña y sostenible que cabe dentro de una semana saludable vale más que tres ambiciosas que se derrumban bajo su propio peso. Piénsalo como sembrar y no como correr una carrera de velocidad. Las semillas se ponen en la tierra y luego se les da tiempo.",
      ],
    },
    {
      title: "La práctica: haz un inventario",
      body: [
        "La práctica de este primer río es deliberadamente sencilla. No se te pide que empieces un negocio ni que agregues tres fuentes de ingresos para el viernes. Se te pide que mires con honestidad lo que ya existe. Abre el registro de abajo y agrega cada fuente distinta de dinero de tu vida como una entrada propia. Ponle nombre, elige la categoría más cercana, anota un monto habitual y elige con qué frecuencia llega. Incluye las fuentes obvias, como tu trabajo principal, y las que se olvidan fácil, como los intereses, el trabajo extra ocasional o un arreglo familiar.",
        "Al anotarlas notarás algo. Ver tus fuentes lado a lado cambia cómo se sienten. Un hogar que se consideraba viviendo de un solo sueldo puede encontrar tres fuentes pequeñas que nunca había contado. Un hogar que se sentía diversificado puede descubrir que el noventa por ciento de su ingreso pasa por un solo cauce. Ningún descubrimiento es un veredicto. Ambos son información, y la información es lo que mueve a la mayordomía.",
        "Mientras tienes tus fuentes frente a ti, hay una cosa más que vale la pena ver. Una fuente adicional, aunque sea pequeña, trae ingresos sin sumar ni una sola cuenta, así que casi todo se convierte en dinero opcional, la parte que queda después de los gastos. Para un hogar al que le sobra poco cada mes, una fuente modesta puede multiplicar ese número. Un hogar con cuatrocientos dólares de sobra después de los gastos que agrega cuatrocientos dólares de ingreso nuevo lo ha duplicado, y la diferencia se repite cada mes y crece con los años. El dinero opcional adicional puede ir a muchos lugares. Una forma muy conocida en que algunos hogares lo usan con la deuda es la bola de nieve de deudas: pagar el mínimo de cada deuda, poner cada dólar extra en el saldo más pequeño y, cuando se salda, pasar todo su pago a la siguiente. En la aritmética, eso puede acortar mucho el camino hacia quedar libre de deudas. La calculadora de abajo te permite explorar todo esto con números de ejemplo: cómo las fuentes adicionales cambian el dinero opcional, qué hace una bola de nieve con un conjunto de deudas y cómo podrían verse año por año los ingresos, el dinero opcional, la deuda, el ahorro y las inversiones. Es un \"¿y si...?\", no un consejo, y a dónde debe ir el dinero extra es una decisión tuya y de las personas en quienes confías.",
        "Jesús dijo que el que es fiel en lo muy poco, también es fiel en lo mucho. Contar lo que tienes es algo muy pequeño, pero es el primer acto de fidelidad con ello. Es también lo que la mayoría de las personas nunca hace. El registro sumará un equivalente mensual aproximado de tus fuentes recurrentes, que puedes tomar como una imagen inicial y no como una cifra exacta.",
        "Algunos obstáculos suelen aparecer en este punto, y es mejor nombrarlos ahora. El primero es la vergüenza: algunas fuentes se sienten demasiado pequeñas para contarlas. Cuéntalas de todos modos. El segundo es la duda sobre las categorías: si una entrada no encaja bien, escoge la más cercana y sigue adelante, porque las categorías son solo para tu propia organización. El tercero son los ingresos irregulares. Si una fuente varía mucho, anota un monto habitual conservador y usa una nota para recordar el rango. El registro no es un examen, y una estimación honesta siempre es mejor que una perfecta que nunca terminas.",
        "Cuando termines, reflexiona sobre algunas preguntas. ¿De qué fuente dependo más, y qué pasaría si se detuviera mañana? ¿Cuál de mis fuentes está creciendo y cuál se está encogiendo en silencio? ¿Hay una habilidad, un activo o una etapa de la vida que podría sostener una fuente adicional sin costarme mi descanso o mi integridad? Escribe tus respuestas honestas si eso te ayuda. No necesitas actuar todavía. Solo necesitas ver con claridad. Cuando hayas anotado al menos una entrada y leído esta lección, el primer río estará completo y se abrirá el segundo.",
      ],
    },
  ],
};
