import type { Lesson } from "../../types";
import { VERSE } from "../scripture";

export const river2: Lesson = {
  riverNumber: 2,
  title: "Saving",
  intro:
    "A river that is only ever drawn from will eventually run dry, and a river that is never held back will flood and then vanish. The second river of the course is about the wise middle: holding some of what flows in, on purpose, before it is spent. Saving is one of the least glamorous spiritual practices, and one of the most consistently praised in Scripture. In this lesson we will look at why a reservoir matters, how saving differs from hoarding, how to give your savings a name and a plan, why small and regular beats large and occasional, how to prepare for hard seasons and for the people who depend on you, and how debt and discontent quietly drain the reservoir. At the end you will set up one savings goal and log a first contribution toward it.",
  introScripture: [VERSE.prov21_20_nlt],
  sections: [
    {
      heading: "Why a river needs a reservoir",
      body: [
        "Imagine a town built beside a river that flows generously in spring and shrinks to a trickle in late summer. The wise town builds a reservoir. In the season of abundance it collects and holds water, and in the season of scarcity it releases it. The reservoir does not make the river any bigger. It changes when the water is available. That is exactly what saving does with money. It moves some of the abundance of a good season into a hard one, so that the hard one does not have to be survived on a trickle.",
        "The clearest biblical picture of this is Joseph in Egypt. Pharaoh dreamed of seven fat years followed by seven lean ones, and Joseph advised gathering the food of the good years and laying it up in the cities, so that the land would not perish through the famine. Notice that Joseph did not predict the famine because he was gifted at economics. He was told what was coming. Most of us are not told. But we know from ordinary life that lean seasons do come: a medical bill, a car that dies, a lost job, a slow year in business. We simply do not know when.",
        "The ant appears in Proverbs as a teacher for exactly this reason. It is described as a creature not strong, yet it prepares its food in the summer. The lesson is not that ants are wise thinkers. It is that preparation does not require great strength or great income. It requires the habit of setting something aside while the season is kind. Proverbs also says that there is treasure to be desired in the house of the wise, but that a foolish person spends it all. The difference between the two is not what they earn. It is what they keep.",
        "This is worth stating plainly because many people assume saving is only for those with a lot left over. In practice, the reverse is closer to the truth. Those with little margin have the most to lose from a single surprise, and so they have the strongest reason to begin, even if the beginning is small.",
      ],
      scriptureRefs: [VERSE.gen41_35_kjv, VERSE.prov30_25_kjv, VERSE.prov21_20_niv],
    },
    {
      heading: "Saving is not hoarding",
      body: [
        "Any honest teaching on saving has to deal with the warnings Jesus gave about wealth, because it is easy to hear praise for saving and slide into something Jesus condemned. On one occasion a man in a crowd asked Jesus to settle an inheritance dispute. Jesus responded by telling everyone to take care and be on guard against all covetousness, because a person's life does not consist in the abundance of his possessions. Then he told a story.",
        "In the story, a farmer has an extraordinary harvest. He decides to tear down his barns and build bigger ones, and then to tell himself to relax, eat, drink, and be merry. God calls him a fool, because that very night his life would be required of him, and everything he had stored would belong to someone else. The story ends with a line worth memorizing: so is the person who lays up treasure for himself and is not rich toward God.",
        "What was wrong with the farmer? It was not that he stored grain. Joseph stored grain, and that was wise. The trouble was that the storage was entirely for himself, the plan had no room for God or neighbor, and the security he was buying was a false one, the kind that says my life is safe because my barns are full. In the Sermon on the Mount, Jesus makes the same point from another angle: do not lay up treasures on earth, where moth and rust destroy, but lay up treasures in heaven, because where your treasure is, there your heart will be also.",
        "So how do we tell saving from hoarding? A few markers help. Saving has a purpose: it is aimed at a need, a goal, or a calling. Hoarding has no destination except more. Saving is compatible with generosity, and often makes it possible. Hoarding tightens its grip when someone needs help. Saving lets you sleep. Hoarding demands that you keep checking. If your savings are making you more free, more generous, and more at rest, they are doing their job. If they are making you more anxious, more guarded, and more resentful of requests, look again at your heart.",
      ],
      scriptureRefs: [VERSE.luke12_15_esv, VERSE.luke12_20_kjv, VERSE.matt6_19_esv],
    },
    {
      heading: "Name the goal, plan the work",
      body: [
        "Money without a destination tends to find one. That is the unglamorous truth behind most failed attempts to save. People decide to save whatever is left at the end of the month, and at the end of the month, nothing is left, because a month is very good at using up everything it is given. The remedy is to give savings a name and a number before the month begins.",
        "A good savings goal answers three questions. What is this for? How much do I need? By when? An emergency fund might be a cushion of three to six months of essential expenses. A replacement vehicle might be a specific amount by a specific year. A first home, a family trip, a wedding, an education, or a ministry commitment all become concrete once you write them down. The name matters emotionally. It is much easier to make a small sacrifice for the new roof than for the abstract idea of being responsible.",
        "Proverbs says that the plans of the diligent lead surely to abundance, but everyone who is hasty comes only to poverty. Another proverb gives an order of operations for a farmer: prepare your work outside and get everything ready in the field, and after that build your house. The principle is that the foundation comes before the finish. In household terms, the reserve comes before the luxuries, and the plan comes before the purchase. Saving is the field work of a financial life. It is not exciting, but the house depends on it.",
        "Here is what a named goal can look like in practice. Instead of a vague intention to build some savings, a household writes: a starter emergency cushion of one thousand dollars, by the end of March, at twenty-five dollars each week. Notice that the sentence contains a purpose, an amount, a deadline, and a rhythm. Anyone reading it can tell at a glance whether it is on track. A goal like that also gives you a natural moment of celebration, which matters more than it sounds. People keep habits that they are allowed to enjoy finishing.",
        "It also helps to sequence your goals rather than pursue them all at once. Most people find it wise to build a small starter cushion first, then address any high-cost debt, then build the cushion to its full size, and then pursue longer goals such as a down payment or education. The exact sequence depends on your situation, and this course is not personal advice. The point is that goals work better in an order than in a jumble.",
      ],
      scriptureRefs: [VERSE.prov21_5_esv, VERSE.prov24_27_esv],
    },
    {
      heading: "Little by little",
      body: [
        "One of the most encouraging verses in Proverbs for anyone who feels behind is this: dishonest money dwindles away, but whoever gathers money little by little makes it grow. The phrase little by little is the whole secret of ordinary saving. The wealth that lasts is rarely built by dramatic windfalls. It is built by small, regular acts repeated for a long time, long enough that they stop feeling like sacrifices and start feeling like habits.",
        "The prophet Zechariah asked a question that fits here: who has despised the day of small things? It is a gentle rebuke to the instinct that says a small contribution is not worth making. A modest deposit does not look like much on the day you make it. But it does three things that a large occasional deposit cannot. It builds the habit. It keeps the goal in front of you. And it survives changes of mood, because it was decided in advance rather than felt in the moment.",
        "Paul gave the church at Corinth a practical rhythm for setting money aside. On the first day of every week, each of them was to put something aside and store it up as they were able to prosper, so that no collections would have to be made in a hurry when he arrived. Two features stand out. It was regular, weekly rather than sporadic. And it was proportional, according to how they had prospered rather than a fixed amount that ignored their circumstances.",
        "What if there is truly almost nothing left each month? This is a real situation for many faithful, hardworking people, and it deserves a real answer rather than a slogan. Start smaller than feels respectable. A few dollars a week is not a joke. It builds the habit, proves to yourself that the practice is possible, and gives you something to grow when circumstances improve. Then look for one honest place to loosen the pressure, whether that is income, expenses, or both. Progress at this level is measured in direction, not size. A person who saves five dollars a week is farther along than a person who saves nothing and intends to save a great deal.",
        "There is an old piece of advice worth borrowing here: pay yourself first. If you wait until the end of the month to see what is left, your saving will always be an afterthought. If you move a set amount to your goal at the moment income arrives, saving becomes a decision you made once, rather than a decision you must win every day. Many people automate this. Whether or not you do, choose an amount small enough that you will actually keep it, and let it grow as your capacity grows.",
      ],
      scriptureRefs: [VERSE.prov13_11_niv, VERSE.zech4_10_kjv],
    },
    {
      heading: "For the hard season and the people who depend on you",
      body: [
        "Proverbs observes that a prudent person sees danger and takes refuge, while the simple keep going and suffer for it. The point is not that the prudent are pessimists. It is that they respond to visible risk while there is still time. Almost every household faces some risks that are visible in advance: a car that is getting old, a health condition, a job in a struggling industry, a home with an aging roof. An emergency fund is the practical form of taking refuge. It is a room you build before the storm.",
        "The psalmist gives an encouraging promise in this direction. The Lord knows the days of the blameless, and their heritage will remain forever. They will not be put to shame in evil times, and in the days of famine they will have abundance. This is not a promise that faithful people never face hardship. It is a promise that God sustains them in it. Saving is one of the ways he often does so. When you build a reserve, you are cooperating with the way he provides.",
        "Saving also has a relational side. Paul writes that anyone who does not provide for his relatives, and especially for his own household, has denied the faith. That is a strong sentence, and it should be read with care. It is not aimed at people who are poor or unlucky. It is aimed at those who could provide and will not. For parents, spouses, and adult children of aging parents, savings are often the concrete form of love. They are what let a family absorb a shock without falling apart.",
        "Proverbs goes further and says that a good person leaves an inheritance for his children's children. For most families that inheritance will be modest, and it need not be measured in money alone. But the instinct behind it is healthy: to think a generation ahead, to leave those who follow you better prepared than you were. Even a small habit of saving, passed on in example, is a form of inheritance. Children who watch their parents save patiently tend to learn something no lecture could teach.",
      ],
      scriptureRefs: [VERSE.prov22_3_kjv, VERSE.ps37_18_esv, VERSE.tim5_8_niv, VERSE.prov13_22_niv],
    },
    {
      heading: "Debt, contentment, and the enemy of saving",
      body: [
        "If saving is filling a reservoir, debt is a hole in its floor. Proverbs states it plainly: the rich rule over the poor, and the borrower is the slave of the lender. Paul says, owe no one anything except to love one another. These verses are not a blanket prohibition on every kind of borrowing, and thoughtful Christians disagree about where the lines fall. But they describe a real pattern. Debt reduces freedom. It commits a portion of tomorrow's income to yesterday's purchases, and it makes it harder to give, to save, or to say no to a bad job.",
        "For that reason, most practical teaching on saving includes some plan for debt. High-interest consumer debt in particular tends to cancel out the benefit of saving, because the interest you pay often exceeds anything your savings could earn. Many people find it wise to build a small emergency cushion first, so that a surprise does not push them back into borrowing, and then to pay down costly debt with focus while continuing to save something. The order and the amounts depend on your circumstances, and a trusted, licensed professional can help you weigh them.",
        "Underneath the mechanics is a spiritual issue: contentment. Paul wrote to the Philippians that he had learned, in whatever state he was, to be content. Notice the word learned. Contentment was not his natural condition. It was a skill he acquired, often the hard way. Much overspending is not driven by need but by comparison, by a quiet sense that we are behind and that a purchase will put us right. Contentment does not mean we never enjoy things or improve our lives. It means our sense of enough does not rise every time our income does.",
        "One practical way to grow it is to wait. Give any nonessential purchase over a certain amount a cooling-off period of a few days. Many desires evaporate on their own. The ones that survive are usually the ones worth considering. Every time you wait and do not spend, you have made a small deposit in the reservoir, and you have practiced the art of enough.",
      ],
      scriptureRefs: [VERSE.prov22_7_kjv, VERSE.rom13_8_kjv, VERSE.phil4_11_kjv],
    },
    {
      heading: "The practice: set one goal and make the first deposit",
      body: [
        "Your practice for the second river is to set up one savings goal and log a first contribution toward it. Choose something specific and meaningful, even if it is small. If you are not sure where to start, an emergency fund is a sensible first goal for many households, and a modest starting target, such as one month of essential expenses, is far less intimidating than a large one. Name the goal, give it a target amount, and then use the quick steppers or the custom field to log your first deposit.",
        "The tracker records every contribution as its own entry, and your running balance is always the sum of those entries. Nothing is assumed and nothing is estimated, which means the number you see is a true picture of what you have actually set aside. If you make a mistake, you can delete an entry, and the balance will correct itself. The habit you are building is not perfection. It is honesty with a small number, repeated.",
        "The stepper is designed for a rhythm. If you save the same amount each week or each payday, tap the plus for that amount each time. Over the course of a few months, the count next to it becomes a quiet record of your faithfulness. Paul's instruction to set something aside on the first day of every week is the ancestor of this idea. Regularity is the point.",
        "As you finish, consider a few questions. What is this goal really for, beneath the number? Whom does it protect? What is the smallest amount I could commit to that I would honestly keep? What is the one habit or expense that most often eats my saving, and what would it look like to loosen its hold? Write your answers in the journal if that helps. A slack hand causes poverty, Proverbs says, but the hand of the diligent makes rich. Diligence here does not mean intensity. It means showing up, in small ways, for a long time. When you have read this lesson and logged a contribution, the second river is complete and the third will open.",
      ],
      scriptureRefs: [VERSE.cor16_2_esv, VERSE.prov10_4_esv],
    },
  ],
  practicePrompt: "Create one savings goal and log your first contribution toward it.",
  practiceScripture: [VERSE.cor4_2_kjv],
};
